In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [9]:
df = pd.read_csv("D:\\DATASET\\Covid_data.csv")

In [10]:
df.head()

   age Body Temp  Chronic disease  Blood O2 Level in Percentage  Anti Bodies
0   10  Moderate                0                            97       127181
1   80      High                0                            92        61004
2   10       Low                0                            97       111911
3   81      High                4                            75        39010
4   12  Moderate                0                            97       110911

In [11]:
df.tail()

    age Body Temp  Chronic disease  Blood O2 Level in Percentage  Anti Bodies
65   76      High                4                            80        39010
66   35  Moderate                0                            92        91141
67   13  Moderate                0                            94       112101
68   82      High                3                            73        42010
69   84      High                3                            75        42099

In [12]:
df.columns

Index(['age', 'Body Temp', 'Chronic disease', 'Blood O2 Level in Percentage',
       'Anti Bodies'],
      dtype='object')

In [15]:
df.describe

<bound method NDFrame.describe of     age Body Temp  Chronic disease  Blood O2 Level in Percentage  Anti Bodies
0    10  Moderate                0                            97       127181
1    80      High                0                            92        61004
2    10       Low                0                            97       111911
3    81      High                4                            75        39010
4    12  Moderate                0                            97       110911
..  ...       ...              ...                           ...          ...
65   76      High                4                            80        39010
66   35  Moderate                0                            92        91141
67   13  Moderate                0                            94       112101
68   82      High                3                            73        42010
69   84      High                3                            75        42099

[70 rows x 5 columns]>