In [3]:
import pandas as pd

In [4]:
pd.read_csv("customers-100.csv")

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [5]:
df=(pd.read_csv("customers-100.csv"))

In [6]:
df

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [7]:
df.columns

Index(['Index', 'Customer Id', 'First Name', 'Last Name', 'Company', 'City',
       'Country', 'Phone 1', 'Phone 2', 'Email', 'Subscription Date',
       'Website'],
      dtype='object')

In [8]:
df.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

In [9]:
df.tail()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [10]:
df.dtypes

Index                 int64
Customer Id          object
First Name           object
Last Name            object
Company              object
City                 object
Country              object
Phone 1              object
Phone 2              object
Email                object
Subscription Date    object
Website              object
dtype: object

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              100 non-null    int64
 1   Customer Id        100 non-null    object
 2   First Name         100 non-null    object
 3   Last Name          100 non-null    object
 4   Company            100 non-null    object
 5   City               100 non-null    object
 6   Country            100 non-null    object
 7   Phone 1            100 non-null    object
 8   Phone 2            100 non-null    object
 9   Email              100 non-null    object
 10  Subscription Date  100 non-null    object
 11  Website            100 non-null    object
dtypes: int64(1), object(11)
memory usage: 9.5+ KB

In [12]:
df.describe()# staistical info about numerical column

            Index
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000

In [13]:
# five point summury>> min, 25% , 50%, 75%, max

In [14]:
# when wanna subset of data
df[["City", "Country" ,"Company"]]

,City,Country,Company
0,East Leonard,Chile,Rasmussen Group
1,East Jimmychester,Djibouti,Vega-Gentry
2,Isabelborough,Antigua and Barbuda,Murillo-Perry
3,Bensonview,Dominican Republic,"Dominguez, Mcmillan and Donovan"
4,West Priscilla,Slovakia (Slovak Republic),"Martin, Lang and Andrade"
...,...,...,...
95,East Richard,Guyana,Carey LLC
96,New Bradview,Sri Lanka,"Ware, Burns and Oneal"
97,Ortegaland,Solomon Islands,Schmitt-Jones
98,Lake Elijahview,Aruba,Fitzgerald-Harrell
99,Judymouth,Honduras,"Le, Nash and Cross"

In [15]:
df.dtypes

Index                 int64
Customer Id          object
First Name           object
Last Name            object
Company              object
City                 object
Country              object
Phone 1              object
Phone 2              object
Email                object
Subscription Date    object
Website              object
dtype: object

In [16]:
# if you wanna a column name which are the objects
df.dtypes=="object"# object is a string datatype # printing the true where object were present

Index                False
Customer Id           True
First Name            True
Last Name             True
Company               True
City                  True
Country               True
Phone 1               True
Phone 2               True
Email                 True
Subscription Date     True
Website               True
dtype: bool

In [17]:
df.dtypes[df.dtypes=="object"]# returns only those value where condition is true

Customer Id          object
First Name           object
Last Name            object
Company              object
City                 object
Country              object
Phone 1              object
Phone 2              object
Email                object
Subscription Date    object
Website              object
dtype: object

In [18]:
#to get the index
df.dtypes[df.dtypes=="object"].index # these are the actully string column

Index(['Customer Id', 'First Name', 'Last Name', 'Company', 'City', 'Country',
       'Phone 1', 'Phone 2', 'Email', 'Subscription Date', 'Website'],
      dtype='object')

In [19]:
df[df.dtypes[df.dtypes=="object"].index]# string data

,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...
95,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [20]:
#numerical data
df[df.dtypes[df.dtypes!="object"].index]

    Index
0       1
1       2
2       3
3       4
4       5
..    ...
95     96
96     97
97     98
98     99
99    100

[100 rows x 1 columns]

In [21]:
#when wnats to describe the numerical data
df[df.dtypes[df.dtypes!="object"].index].describe() # write a correct describe name dont make any spelling mistake

            Index
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000

In [22]:
df.describe()# numerical column

            Index
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000

In [23]:
df.describe(include ="object")# for the uniqueness of the evry column

,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
count,100,100,100,100,100,100,100,100,100,100,100
unique,100,93,97,99,100,85,100,100,100,96,100
top,DD37Cf93aecA6Dc,Sheryl,Greer,Simon LLC,East Leonard,Solomon Islands,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2021-12-02,http://www.stephenson.com/
freq,1,2,2,2,1,4,1,1,1,2,1

In [24]:
# all info murge together
df.describe(include ="all")

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
count,100.000000,100,100,100,100,100,100,100,100,100,100,100
unique,NaN,100,93,97,99,100,85,100,100,100,96,100
top,NaN,DD37Cf93aecA6Dc,Sheryl,Greer,Simon LLC,East Leonard,Solomon Islands,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2021-12-02,http://www.stephenson.com/
freq,NaN,1,2,2,2,1,4,1,1,1,2,1
mean,50.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,29.011492,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,25.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,50.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,75.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,100.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df.shape#100 rows and 12 column

(100, 12)

In [26]:
#when wanna aceess 0 to 100 row 
df[0:100]

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [27]:
# when wnats after every fifth element
df[0:100:5]# distance will be 0,5,10, 15 like that

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
5,6,2d08FB17EE273F4,Aimee,Downs,Steele Group,Chavezborough,Bosnia and Herzegovina,(283)437-3886x88321,999-728-1637,louis27@gilbert.com,2020-02-25,http://www.berger.net/
10,11,216E205d6eBb815,Carl,Schroeder,"Oconnell, Meza and Everett",Shannonville,Guernsey,637-854-0256x825,114.336.0784x788,kirksalas@webb.com,2021-10-20,https://simmons-hurley.com/
15,16,8cad0b4CBceaeec,Miranda,Beasley,Singleton and Sons,Desireeshire,Oman,540.085.3135x185,+1-600-462-6432x21881,vduncan@parks-hardy.com,2022-04-12,http://acosta.org/
20,21,9F9AdB7B8A6f7F2,Maxwell,Frye,Patterson Inc,East Carly,Malta,423.262.3059,202-880-0688x7491,fgibson@drake-webb.com,2022-01-12,http://www.roberts.com/
25,26,09D7D7C8Fe09aea,Marcus,Moody,Giles Ltd,Kaitlyntown,Panama,674-677-8623,909-277-5485x566,donnamullins@norris-barrett.org,2022-05-24,https://www.curry.com/
30,31,64DCcDFaB9DFd4e,Jack,Tate,"Acosta, Petersen and Morrow",West Samuel,Zimbabwe,965-108-4406x20714,046.906.1442x6784,gfigueroa@boone-zavala.com,2021-09-15,http://www.hawkins-ramsey.com/
35,36,E11dfb2DB8C9f72,Tammie,Haley,"Palmer, Barnes and Houston",East Teresa,Belize,001-276-734-4113x6087,(430)300-8770,harrisisaiah@jenkins.com,2022-01-04,http://evans-simon.com/
40,41,2f79Cd309624Abb,Natalie,Gentry,Monroe PLC,West Darius,Dominican Republic,830.996.8238,499.122.5415,tcummings@fitzpatrick-ashley.com,2020-10-10,http://www.dorsey.biz/
45,46,fD780ED8dbEae7B,Joanne,Montes,"Price, Sexton and Mcdaniel",Gwendolynview,Palau,(897)726-7952,(467)886-9467x5721,juan80@henson.net,2020-07-01,http://ochoa.com/
50,51,Aa20BDe68eAb0e9,Gerald,Hawkins,"Phelps, Forbes and Koch",New Alberttown,Canada,+1-323-239-1456x96168,(092)508-0269,uwarner@steele-arias.com,2021-03-19,https://valenzuela.com/
55,56,C6F2Fc6a7948a4e,Ralph,Haas,Montes PLC,Lake Ellenchester,Palestinian Territory,2239271999,001-962-434-0867x649,goodmancesar@figueroa.biz,2020-05-25,http://may.com/
60,61,a940cE42e035F28,Lynn,Pham,"Brennan, Camacho and Tapia",East Pennyshire,Portugal,846.468.6834x611,001-248-691-0006,mpham@rios-guzman.com,2020-08-21,https://www.murphy.com/
65,66,fF1b6c9E8Fbf1ff,Fernando,Lambert,Church-Banks,Lake Nancy,Lithuania,497.829.9038,3863743398,fisherlinda@schaefer.net,2021-04-23,https://www.vang.com/
70,71,CBCd2Ac8E3eBDF9,Alexandria,Buck,Keller-Coffey,Nicolasfort,Iran,078-900-4760x76668,414-112-8700x68751,lee48@manning.com,2021-02-20,https://ramsey.org/
75,76,d40e89dCade7b2F,Debra,Riddle,"Chang, Aguirre and Leblanc",Colinhaven,United States Virgin Islands,+1-768-182-6014x14336,(303)961-4491,shieldskerry@robles.com,2020-07-11,http://kaiser.info/
80,81,D6CEAfb3BDbaa1A,Leslie,Jennings,Blankenship-Arias,Coreybury,Micronesia,629.198.6346,075.256.0829,corey75@wiggins.com,2021-11-13,https://www.juarez.com/
85,86,C6763c99d0bd16D,Emma,Cunningham,Stephens Inc,North Jillianview,New Zealand,128-059-0206x60217,(312)164-4545x2284,walter83@juarez.org,2022-05-13,http://www.reid.info/
90,91,5ef6d3eefdD43bE,Nina,Chavez,Byrd-Campbell,Cassidychester,Bhutan,053-344-3205,+1-330-920-5422x571,elliserica@frank.com,2020-03-26,https://www.pugh.com/
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/

In [28]:
df.astype('object').describe()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
count,100,100,100,100,100,100,100,100,100,100,100,100
unique,100,100,93,97,99,100,85,100,100,100,96,100
top,1,DD37Cf93aecA6Dc,Sheryl,Greer,Simon LLC,East Leonard,Solomon Islands,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2021-12-02,http://www.stephenson.com/
freq,1,1,2,2,2,1,4,1,1,1,2,1

In [29]:
#for adding the new column, data name is pwskills and col name is new_column
df["new_col"] = "pwskills"

In [30]:
df

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website,new_col
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/,pwskills
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/,pwskills
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/,pwskills
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/,pwskills
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/,pwskills
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/,pwskills
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/,pwskills
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/,pwskills
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/,pwskills
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/,pwskills

In [37]:
# when create a new column from the existing column
#......df["family"] = df["index"]+df["Customer_id"]..... # not run bcz having no data for adding two will show in three like 1+2=3

In [38]:
df.info

<bound method DataFrame.info of     Index      Customer Id First Name Last Name  \
0       1  DD37Cf93aecA6Dc     Sheryl    Baxter
1       2  1Ef7b82A4CAAD10    Preston    Lozano
2       3  6F94879bDAfE5a6        Roy     Berry
3       4  5Cef8BFA16c5e3c      Linda     Olsen
4       5  053d585Ab6b3159     Joanna    Bender
..    ...              ...        ...       ...
95     96  cb8E23e48d22Eae       Karl     Greer
96     97  CeD220bdAaCfaDf       Lynn  Atkinson
97     98  28CDbC0dFe4b1Db       Fred    Guerra
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer
99    100  2354a0E336A91A1   Clarence    Haynes

                            Company               City  \
0                   Rasmussen Group       East Leonard
1                       Vega-Gentry  East Jimmychester
2                     Murillo-Perry      Isabelborough
3   Dominguez, Mcmillan and Donovan         Bensonview
4          Martin, Lang and Andrade     West Priscilla
..                              ...                ...
95                        Carey LLC       East Richard
96            Ware, Burns and Oneal       New Bradview
97                    Schmitt-Jones         Ortegaland
98               Fitzgerald-Harrell    Lake Elijahview
99               Le, Nash and Cross          Judymouth

                       Country                 Phone 1  \
0                        Chile            229.077.5154
1                     Djibouti              5153435776
2          Antigua and Barbuda         +1-539-402-0259
3           Dominican Republic  001-808-617-6467x12895
4   Slovakia (Slovak Republic)  001-234-203-0635x76146
..                         ...                     ...
95                      Guyana     (188)169-1674x58692
96                   Sri Lanka         +1-846-706-2218
97             Solomon Islands    +1-753-067-8419x7170
98                       Aruba           (530)311-9786
99                    Honduras           (753)813-6941

                   Phone 2                           Email Subscription Date  \
0         397.884.0519x718        zunigavanessa@smith.info        2020-08-24
1         686-620-1820x944                 vmata@colon.com        2021-04-23
2      (496)978-3969x58947             beckycarr@hogan.com        2020-03-25
3          +1-813-324-8756     stanleyblackwell@benson.org        2020-06-02
4    001-199-446-3860x3486         colinalvarado@miles.net        2021-04-17
..                     ...                             ...               ...
95    001-841-293-3519x614                hhart@jensen.com        2022-01-30
96            605.413.3198               vkemp@ferrell.com        2021-07-10
97   +1-632-666-7507x92121                swagner@kane.org        2021-09-18
98  001-869-452-0943x12424  mccarthystephen@horn-green.biz        2021-08-11
99            783.639.1472          colleen91@faulkner.biz        2020-03-11

                              Website   new_col
0          http://www.stephenson.com/  pwskills
1               http://www.hobbs.com/  pwskills
2            http://www.lawrence.com/  pwskills
3          http://www.good-lyons.com/  pwskills
4         https://goodwin-ingram.com/  pwskills
..                                ...       ...
95            http://hayes-perez.com/  pwskills
96         https://novak-allison.com/  pwskills
97              https://www.ross.com/  pwskills
98               http://watkins.info/  pwskills
99  http://www.hatfield-saunders.net/  pwskills

[100 rows x 13 columns]>

In [40]:
df['City'].unique() # showing the unique value which is in the present

array(['East Leonard', 'East Jimmychester', 'Isabelborough', 'Bensonview',
       'West Priscilla', 'Chavezborough', 'Lake Ana', 'Kimport',
       'Robersonstad', 'Elaineberg', 'Shannonville', 'East Andrea',
       'South Joannamouth', 'Jodyberg', 'Burchbury', 'Desireeshire',
       'West Adriennestad', 'Lake Leslie', 'Harmonview', 'Jamesshire',
       'East Carly', 'South Alvin', 'Brittanyview', 'Veronicamouth',
       'Bryanville', 'Kaitlyntown', 'Michealshire', 'South Marissatown',
       'Acevedoville', 'North Harold', 'West Samuel', 'Cunninghamborough',
       'Port Annatown', 'New Kaitlyn', 'West Marthaburgh', 'East Teresa',
       'South Hunter', 'South Walter', 'Poolefurt', 'West John',
       'West Darius', 'North Jimstad', 'East Rebekahborough',
       'North Drew', 'Lake Lindaburgh', 'Gwendolynview', 'Zimmermanland',
       'North Kerriton', 'North Eileenville', 'Port Sergiofort',
       'New Alberttown', 'South Jasmine', 'Cowanfort', 'New Deborah',
       'Wallstown', 'Lake Ellenchester', 'Lake Whitney', 'East Jaredbury',
       'Selenabury', 'Huangfort', 'East Pennyshire', 'Port Jasminborough',
       'West Kristine', 'South Julia', 'Helenborough', 'Lake Nancy',
       'Georgeport', 'South Sophiaberg', 'Hartbury', 'Erikaville',
       'Nicolasfort', 'New Jasmineshire', 'East Summerstad',
       'Skinnerport', 'Raystad', 'Colinhaven', 'West Reginald',
       'Lake Sherryborough', 'Port Katherineville', 'Thomasland',
       'Coreybury', 'Lake Janiceton', 'East Clinton', 'South Joshuashire',
       'New Glenda', 'North Jillianview', 'Lyonsberg',
       'East Cristinabury', 'Thomasfurt', 'North Joeburgh',
       'Cassidychester', 'South Dannymouth', 'South Lonnie',
       'Frankchester', 'Daisyborough', 'East Richard', 'New Bradview',
       'Ortegaland', 'Lake Elijahview', 'Judymouth'], dtype=object)

In [41]:
df['Email'].unique()

array(['zunigavanessa@smith.info', 'vmata@colon.com',
       'beckycarr@hogan.com', 'stanleyblackwell@benson.org',
       'colinalvarado@miles.net', 'louis27@gilbert.com',
       'tgates@cantrell.com', 'asnow@colon.com',
       'mariokhan@ryan-pope.org', 'mdyer@escobar.net',
       'kirksalas@webb.com', 'mark42@robbins.com', 'alex56@walls.org',
       'holdenmiranda@clarke.com', 'cassieparrish@blevins-chapman.net',
       'vduncan@parks-hardy.com', 'holtgwendolyn@watson-davenport.com',
       'jaredjuarez@carroll.org', 'joseph26@jacobson.com',
       'tuckerangie@salazar.net', 'fgibson@drake-webb.com',
       'blanchardbob@wallace-shannon.com', 'rsingleton@ryan-cherry.com',
       'stefanie71@spence.com', 'mariah88@santos.com',
       'donnamullins@norris-barrett.org', 'stacey67@fields.org',
       'jacobkhan@bright.biz', 'wterrell@clark.com', 'qjimenez@boyd.com',
       'gfigueroa@boone-zavala.com', 'tapiagreg@beard.info',
       'coleolson@jennings.net', 'georgeross@miles.org',
       'willistonya@randolph-baker.com', 'harrisisaiah@jenkins.com',
       'fwolfe@dorsey.com', 'tiffanydavies@harris-mcfarland.org',
       'preese@frye-vega.com', 'ann48@miller.com',
       'tcummings@fitzpatrick-ashley.com', 'woodwardandres@phelps.com',
       'barbarapittman@holder.com', 'bstuart@williamson-mcclure.com',
       'zkrueger@wolf-chavez.net', 'juan80@henson.net',
       'bauercrystal@gay.com', 'bartlettjenna@zuniga-moss.biz',
       'mccalltyrone@durham-rose.biz', 'bobhammond@barry.biz',
       'uwarner@steele-arias.com', 'xpittman@ritter-carney.net',
       'vaughanchristy@lara.biz', 'clinton85@colon-arias.org',
       'greenemiranda@zimmerman.com', 'goodmancesar@figueroa.biz',
       'yhanson@warner-diaz.org', 'howelldarren@house-cohen.com',
       'ncamacho@boone-simmons.org', 'kristopher62@oliver.com',
       'mpham@rios-guzman.com', 'zachary96@mitchell-bryant.org',
       'kristiwhitney@bernard.com', 'leah85@sutton-terrell.com',
       'levigiles@vincent.com', 'fisherlinda@schaefer.net',
       'scottcurtis@hurley.biz', 'nicholsonnina@montgomery.info',
       'zvalencia@phelps.com', 'alex06@galloway.com', 'lee48@manning.com',
       'aharper@maddox-townsend.org', 'buckleycory@odonnell.net',
       'angie04@oconnell.com', 'zrosario@rojas-hardin.net',
       'shieldskerry@robles.com', 'mchandler@cochran-huerta.org',
       'katrinalane@fitzgerald.com', 'cookejill@powell.com',
       'elizabethbarr@ewing.com', 'corey75@wiggins.com',
       'chloelester@higgins-wilkinson.com', 'isaac26@benton-finley.com',
       'justinwalters@jimenez.com', 'maurice46@morgan.com',
       'walter83@juarez.org', 'kmercer@wagner.com', 'vcantu@norton.com',
       'hilljesse@barrett.info', 'tyrone77@valenzuela.info',
       'elliserica@frank.com', 'nsteele@sparks.com',
       'dudleyemily@gonzales.biz', 'alan79@gates-mclaughlin.com',
       'grayjean@lowery-good.com', 'hhart@jensen.com',
       'vkemp@ferrell.com', 'swagner@kane.org',
       'mccarthystephen@horn-green.biz', 'colleen91@faulkner.biz'],
      dtype=object)

In [42]:
# when wanna to count the unique value or we can say find how many no. of unique value are present in there
df['City'].nunique()

100

In [49]:
# here we find the company which are repeated 
df['Company'].value_counts()

Company
Simon LLC                      2
Rasmussen Group                1
Knight, Abbott and Hubbard     1
Parrish Ltd                    1
Huynh and Sons                 1
                              ..
Mcgee Group                    1
Acosta, Petersen and Morrow    1
Sawyer PLC                     1
Santana-Duran                  1
Le, Nash and Cross             1
Name: count, Length: 99, dtype: int64

In [50]:
df['City'].value_counts()

City
East Leonard         1
South Julia          1
Skinnerport          1
East Summerstad      1
New Jasmineshire     1
                    ..
West Samuel          1
North Harold         1
Acevedoville         1
South Marissatown    1
Judymouth            1
Name: count, Length: 100, dtype: int64

In [52]:
#how many percent of city are there, here is 1.0 percent each company is there
df['City'].value_counts(normalize=True)*100

City
East Leonard         1.0
South Julia          1.0
Skinnerport          1.0
East Summerstad      1.0
New Jasmineshire     1.0
                    ...
West Samuel          1.0
North Harold         1.0
Acevedoville         1.0
South Marissatown    1.0
Judymouth            1.0
Name: proportion, Length: 100, dtype: float64

In [ ]:
# if we had age then we can also  find blow something date aur above something
#...........df[df['age']<5]........

In [57]:
#df[df['age']<5].shape .....then also can find the no.of rows and no. of columnss ex (40,14) # 40 people whi are less than 5 year old
#df[df['age']<5].name ----- for the print there name who are below thw 5 year old

In [61]:
df['Index'].mean() # for finding the mean of any data ex of age --- wants to mean

50.5

In [62]:
# how many male passangers are there
#----len(df[df['sex'] =="male"---