In [21]:
import pandas as pd

In [22]:
pd.read_csv("rohan.csv")

                Position  Grade   Salary
0          New Associate      1    17000
1              Associate      2    27000
2                Analyst      3    40000
3         Senior Analyst      4    65000
4              Team Lead      5   100000
5      Associate Manager      6   150000
6                Manager      7   250000
7         Senior Manager      8   400000
8             Leadership      9   650000
9      Senior Leadership     10  1000000
10     Global Leadership     12  1800000
11  Executive Leadership     13  4000000

In [23]:
pd.read_csv("rohan.csv",skiprows=2)

              Associate   2    27000
0               Analyst   3    40000
1        Senior Analyst   4    65000
2             Team Lead   5   100000
3     Associate Manager   6   150000
4               Manager   7   250000
5        Senior Manager   8   400000
6            Leadership   9   650000
7     Senior Leadership  10  1000000
8     Global Leadership  12  1800000
9  Executive Leadership  13  4000000

In [24]:
pd.read_csv("rohan.csv",header=None) #internal integer indexes are provided by pandasn for both rows and the column

                       0      1        2
0               Position  Grade   Salary
1          New Associate      1    17000
2              Associate      2    27000
3                Analyst      3    40000
4         Senior Analyst      4    65000
5              Team Lead      5   100000
6      Associate Manager      6   150000
7                Manager      7   250000
8         Senior Manager      8   400000
9             Leadership      9   650000
10     Senior Leadership     10  1000000
11     Global Leadership     12  1800000
12  Executive Leadership     13  4000000

In [25]:
#first two  rows skip while reading the data

In [26]:
pd.read_csv("rohan.csv",skiprows=2)

              Associate   2    27000
0               Analyst   3    40000
1        Senior Analyst   4    65000
2             Team Lead   5   100000
3     Associate Manager   6   150000
4               Manager   7   250000
5        Senior Manager   8   400000
6            Leadership   9   650000
7     Senior Leadership  10  1000000
8     Global Leadership  12  1800000
9  Executive Leadership  13  4000000

In [27]:
#just want to read only three or two column, we use usecols when we wanna to read only columns which we wanna to read

In [28]:
#it should have the actual name of the columns

In [29]:
pd.read_csv("rohan.csv", usecols=[ "Position","Salary"]) # dont make the mistake to write capital should be in the capital first letter

                Position   Salary
0          New Associate    17000
1              Associate    27000
2                Analyst    40000
3         Senior Analyst    65000
4              Team Lead   100000
5      Associate Manager   150000
6                Manager   250000
7         Senior Manager   400000
8             Leadership   650000
9      Senior Leadership  1000000
10     Global Leadership  1800000
11  Executive Leadership  4000000

In [30]:
df=pd.read_csv("rohan.csv")

In [31]:
df

                Position  Grade   Salary
0          New Associate      1    17000
1              Associate      2    27000
2                Analyst      3    40000
3         Senior Analyst      4    65000
4              Team Lead      5   100000
5      Associate Manager      6   150000
6                Manager      7   250000
7         Senior Manager      8   400000
8             Leadership      9   650000
9      Senior Leadership     10  1000000
10     Global Leadership     12  1800000
11  Executive Leadership     13  4000000

In [32]:
#data structure >> series and dataframe
#sereis>>1 dimentional in nature
# dataframe>>2 dimention in nature , multiple series combines to form  a dataframe( rows and column )

In [33]:
type (df)

pandas.core.frame.DataFrame

In [34]:
df.Position # keeps all letter how actually if it sis in caps , it should be in the capas

0            New Associate
1                Associate
2                  Analyst
3           Senior Analyst
4                Team Lead
5        Associate Manager
6                  Manager
7           Senior Manager
8               Leadership
9        Senior Leadership
10       Global Leadership
11    Executive Leadership
Name: Position, dtype: object

In [35]:
df.Grade# first way to access the column

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    12
11    13
Name: Grade, dtype: int64

In [36]:
l=[1,2,3,4]

In [37]:
S= pd.Series(l)# S should be in the caps

In [38]:
S

0    1
1    2
2    3
3    4
dtype: int64

In [39]:
S[1:]

1    2
2    3
3    4
dtype: int64

In [40]:
# by default indexes are the integers , e can have custom index

In [41]:
pd.Series([100, 300, 388], index = ["siya","ram",1]) #firstly pd define by the enter the shift and enter to the main line of the code

siya    100
ram     300
1       388
dtype: int64

In [42]:
d=pd.Series([100, 300, 388], index = ["siya","ram",1])

In [43]:
d

siya    100
ram     300
1       388
dtype: int64

In [44]:
type(d)

pandas.core.series.Series

In [45]:
d["siya"]

100

In [46]:
#to see all the index just use

In [47]:
d.index

Index(['siya', 'ram', 1], dtype='object')

In [48]:
#for the reset the indexing 
d.reset_index(drop=True)

0    100
1    300
2    388
dtype: int64

In [49]:
pd.DataFrame(d)
# D and F  shoud be in the capital

        0
siya  100
ram   300
1     388

In [50]:
df.head(2)
# if getting the error of not define df ,then go the df section and run their and after that u can run hear then it will execute

        Position  Grade  Salary
0  New Associate      1   17000
1      Associate      2   27000

In [51]:
df.tail(2)

                Position  Grade   Salary
10     Global Leadership     12  1800000
11  Executive Leadership     13  4000000

In [52]:
df.shape

(12, 3)

In [53]:
df.columns

Index(['Position', 'Grade', 'Salary'], dtype='object')

In [54]:
list(df.columns)

['Position', 'Grade', 'Salary']

In [55]:
# wannat to see any random row, here it will show thw any random data
df.sample(2)

         Position  Grade  Salary
3  Senior Analyst      4   65000
2         Analyst      3   40000

In [56]:
df.info

<bound method DataFrame.info of                 Position  Grade   Salary
0          New Associate      1    17000
1              Associate      2    27000
2                Analyst      3    40000
3         Senior Analyst      4    65000
4              Team Lead      5   100000
5      Associate Manager      6   150000
6                Manager      7   250000
7         Senior Manager      8   400000
8             Leadership      9   650000
9      Senior Leadership     10  1000000
10     Global Leadership     12  1800000
11  Executive Leadership     13  4000000>

In [57]:
df.dtypes

Position    object
Grade        int64
Salary       int64
dtype: object

In [58]:
df['Position']

0            New Associate
1                Associate
2                  Analyst
3           Senior Analyst
4                Team Lead
5        Associate Manager
6                  Manager
7           Senior Manager
8               Leadership
9        Senior Leadership
10       Global Leadership
11    Executive Leadership
Name: Position, dtype: object

In [59]:
type(df['Position'])

pandas.core.series.Series

In [60]:
list(df['Position'])

['New Associate',
 'Associate',
 'Analyst',
 'Senior Analyst',
 'Team Lead',
 'Associate Manager',
 'Manager',
 'Senior Manager',
 'Leadership',
 'Senior Leadership',
 'Global Leadership',
 'Executive Leadership']

In [61]:
# series to dataframe
s=pd.Series([2,3,4],index=[100,"siya",200])

In [62]:
s

100     2
siya    3
200     4
dtype: int64

In [63]:
d=pd.DataFrame(s)

In [64]:
d

      0
100   2
siya  3
200   4

In [65]:
type(d)

pandas.core.frame.DataFrame

In [66]:
d

      0
100   2
siya  3
200   4

In [67]:
 d["new column"]="siya"

In [68]:
d

      0 new column
100   2       siya
siya  3       siya
200   4       siya

In [69]:
d["new column"]

100     siya
siya    siya
200     siya
Name: new column, dtype: object

In [70]:
d.new column # this will make error bcz pf having the seprate word

SyntaxError: invalid syntax (3580201021.py, line 1)

In [72]:
df

                Position  Grade   Salary
0          New Associate      1    17000
1              Associate      2    27000
2                Analyst      3    40000
3         Senior Analyst      4    65000
4              Team Lead      5   100000
5      Associate Manager      6   150000
6                Manager      7   250000
7         Senior Manager      8   400000
8             Leadership      9   650000
9      Senior Leadership     10  1000000
10     Global Leadership     12  1800000
11  Executive Leadership     13  4000000

In [73]:
 # best way to access the column this way but if its a continous string , you can access using df.column

In [74]:
d["new column"]

100     siya
siya    siya
200     siya
Name: new column, dtype: object

In [75]:
d["new_column"] = [1,2,3] # no of  new column elements should be equals to no of rows

In [76]:
d

      0 new column  new_column
100   2       siya           1
siya  3       siya           2
200   4       siya           3

In [77]:
# change column name
d.columns= [ "col1","col","col3"]

In [78]:
d

      col1   col  col3
100      2  siya     1
siya     3  siya     2
200      4  siya     3

In [79]:
#reset_index
d.reset_index()

  index  col1   col  col3
0   100     2  siya     1
1  siya     3  siya     2
2   200     4  siya     3

In [80]:
d.reset_index(drop=True)

   col1   col  col3
0     2  siya     1
1     3  siya     2
2     4  siya     3

In [81]:
df

                Position  Grade   Salary
0          New Associate      1    17000
1              Associate      2    27000
2                Analyst      3    40000
3         Senior Analyst      4    65000
4              Team Lead      5   100000
5      Associate Manager      6   150000
6                Manager      7   250000
7         Senior Manager      8   400000
8             Leadership      9   650000
9      Senior Leadership     10  1000000
10     Global Leadership     12  1800000
11  Executive Leadership     13  4000000

In [82]:
df[["Position","Grade","Salary"]]
# accessing on column\--series, multiple column(with square bracket becomes a dataframe
 #a subset of dataframe

                Position  Grade   Salary
0          New Associate      1    17000
1              Associate      2    27000
2                Analyst      3    40000
3         Senior Analyst      4    65000
4              Team Lead      5   100000
5      Associate Manager      6   150000
6                Manager      7   250000
7         Senior Manager      8   400000
8             Leadership      9   650000
9      Senior Leadership     10  1000000
10     Global Leadership     12  1800000
11  Executive Leadership     13  4000000

In [83]:
df_subset=df[["Position","Grade","Salary"]]

In [84]:
df_subset

                Position  Grade   Salary
0          New Associate      1    17000
1              Associate      2    27000
2                Analyst      3    40000
3         Senior Analyst      4    65000
4              Team Lead      5   100000
5      Associate Manager      6   150000
6                Manager      7   250000
7         Senior Manager      8   400000
8             Leadership      9   650000
9      Senior Leadership     10  1000000
10     Global Leadership     12  1800000
11  Executive Leadership     13  4000000

In [85]:
type(df_subset)

pandas.core.frame.DataFrame

In [86]:
d["new column"]="siya"

In [87]:
d

      col1   col  col3 new column
100      2  siya     1       siya
siya     3  siya     2       siya
200      4  siya     3       siya

In [88]:
d["new column"] # best way to access the column 
# u can call the column by the using of d.new column but you will get an error bcz of seprate variable name
# if contineous string than can acces by the using of the d.newcolumn

100     siya
siya    siya
200     siya
Name: new column, dtype: object

In [89]:
# can also privide the that no.of list whatever no. of rows are present in it 
# for add new column
d["new_column"]=[1,2,3]

In [90]:
d

      col1   col  col3 new column  new_column
100      2  siya     1       siya           1
siya     3  siya     2       siya           2
200      4  siya     3       siya           3

In [91]:

d.columns

Index(['col1', 'col', 'col3', 'new column', 'new_column'], dtype='object')

In [92]:
# when wants to change the column name
d.columns = ["col1","col2","col3","col4", "col5"]

In [93]:
d

      col1  col2  col3  col4  col5
100      2  siya     1  siya     1
siya     3  siya     2  siya     2
200      4  siya     3  siya     3

In [94]:
#reset index-- hereis in first column name is mention index , if we dont want that then we can use dreo=True

d.reset_index()

  index  col1  col2  col3  col4  col5
0   100     2  siya     1  siya     1
1  siya     3  siya     2  siya     2
2   200     4  siya     3  siya     3

In [95]:
d.reset_index(drop=True)# here is getting col1 than the index in first col

   col1  col2  col3  col4  col5
0     2  siya     1  siya     1
1     3  siya     2  siya     2
2     4  siya     3  siya     3

In [96]:
df

                Position  Grade   Salary
0          New Associate      1    17000
1              Associate      2    27000
2                Analyst      3    40000
3         Senior Analyst      4    65000
4              Team Lead      5   100000
5      Associate Manager      6   150000
6                Manager      7   250000
7         Senior Manager      8   400000
8             Leadership      9   650000
9      Senior Leadership     10  1000000
10     Global Leadership     12  1800000
11  Executive Leadership     13  4000000

In [97]:
#accesing one column its a --series, and when accessing the with multiple column with (square bracket) it will bwcome the dataframe.
df[["Position","Grade","Salary"]]# so its a dataframe

                Position  Grade   Salary
0          New Associate      1    17000
1              Associate      2    27000
2                Analyst      3    40000
3         Senior Analyst      4    65000
4              Team Lead      5   100000
5      Associate Manager      6   150000
6                Manager      7   250000
7         Senior Manager      8   400000
8             Leadership      9   650000
9      Senior Leadership     10  1000000
10     Global Leadership     12  1800000
11  Executive Leadership     13  4000000

In [98]:
df["Grade"]# its a series

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    12
11    13
Name: Grade, dtype: int64

In [105]:
pd.read_excel("sample_employee_data.xlsx")

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   50000
1   2      Bob   30         IT   60000
2   3  Charlie   35    Finance   70000
3   4    David   40  Marketing   80000
4   5      Eva   28      Admin   55000

In [106]:
pip install openpyxl
#this use when other files tha the csv files ,first needs to pip instal then it can be aceess

SyntaxError: invalid syntax (3826350046.py, line 1)

In [107]:
pip install lxml

Requirement already satisfied: lxml in c:\users\ashwini powar\documents\custom office templates\lib\site-packages (5.3.0)
Note: you may need to restart the kernel to use updated packages.

In [108]:
df=(pd.read_html("sample_table.html"))

In [109]:
df

[   ID     Name  Age Department
 0   1    Alice   25         HR
 1   2      Bob   30         IT
 2   3  Charlie   35    Finance
 3   4    David   40  Marketing
 4   5      Eva   28      Admin]

In [110]:
df=(pd.DataFrame())

In [111]:
df.to_csv("output.csv", index=False)
 # write object to a comma-separeted value (csv) files.) # write object to a comma-separeted value (csv) files.
# done to convrt into csv , needed privious process also
# here noneed of the index=false its just for the when indexing dont wanna which is extr column

In [117]:
# read json file
url"filepath"
pd.read_json(url)
#currently dont have the json file thats why i didnt put the file path 
# there is a second way to acess the json file

SyntaxError: invalid syntax (1808638769.py, line 2)

In [124]:
import requests # using the request labrary we can use the json data
data=requests.get(url)

In [125]:
data # 200 means its successful

In [126]:
data.json()# json file data look like the having data in dictionary foemat and also the data in having two of {{}} brachets

{'name': 'John',
 'age': 25,
 'city': 'Sampleville',
 'married': False,
 'hobbies': ['reading', 'traveling', 'programming'],
 'address': {'street': '123 Main Street',
  'city': 'Sample City',
  'postal_code': '12345'}}