In [7]:
import pandas as pd

In [8]:
pd.read_csv("people-100.new.csv")

,Index,User Id,First Name,Last Name,age,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,12,Male,elijah57@example.net,001-084-906-7849x73518,26-10-1945,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,45,Female,bethany14@example.com,214.112.6044x4913,24-03-1910,Phytotherapist
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,34,Male,bthompson@example.com,277.609.7938,02-07-1992,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,23,Male,kaitlinkaiser@example.com,584.094.6111,03-08-2017,Market researcher
4,5,1bA7A3dc874da3c,Lori,Todd,56,Male,buchananmanuel@example.net,689-207-3558x7233,01-12-1938,Veterinary surgeon
...,...,...,...,...,...,...,...,...,...,...
95,96,5eFda7caAeB260E,Dennis,Barnes,64,Female,bmartin@example.org,001-095-524-2112x257,30-07-1954,Software engineer
96,97,CCbFce93d3720bE,Steve,Patterson,34,Female,latasha46@example.net,001-865-478-5157,29-04-1932,Barrister
97,98,2fEc528aFAF0b69,Wesley,Bray,34,Male,regina11@example.org,995-542-3004x76800,28-12-1994,Police officer
98,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,22,Female,alexiscantrell@example.org,001-273-685-6932x092,12-04-2012,Broadcast journalist
99,100,b8D0aD3490FC7e1,Mariah,Bernard,21,Male,pcopeland@example.org,(341)594-6554x44657,15-11-2016,IT sales professional

In [9]:
df=(pd.read_csv("people-100.new.csv"))

In [10]:
df

,Index,User Id,First Name,Last Name,age,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,12,Male,elijah57@example.net,001-084-906-7849x73518,26-10-1945,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,45,Female,bethany14@example.com,214.112.6044x4913,24-03-1910,Phytotherapist
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,34,Male,bthompson@example.com,277.609.7938,02-07-1992,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,23,Male,kaitlinkaiser@example.com,584.094.6111,03-08-2017,Market researcher
4,5,1bA7A3dc874da3c,Lori,Todd,56,Male,buchananmanuel@example.net,689-207-3558x7233,01-12-1938,Veterinary surgeon
...,...,...,...,...,...,...,...,...,...,...
95,96,5eFda7caAeB260E,Dennis,Barnes,64,Female,bmartin@example.org,001-095-524-2112x257,30-07-1954,Software engineer
96,97,CCbFce93d3720bE,Steve,Patterson,34,Female,latasha46@example.net,001-865-478-5157,29-04-1932,Barrister
97,98,2fEc528aFAF0b69,Wesley,Bray,34,Male,regina11@example.org,995-542-3004x76800,28-12-1994,Police officer
98,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,22,Female,alexiscantrell@example.org,001-273-685-6932x092,12-04-2012,Broadcast journalist
99,100,b8D0aD3490FC7e1,Mariah,Bernard,21,Male,pcopeland@example.org,(341)594-6554x44657,15-11-2016,IT sales professional

In [11]:
df.describe()

            Index        age
count  100.000000  100.000000
mean    50.500000   53.970000
std     29.011492   24.842719
min      1.000000   10.000000
25%     25.750000   33.750000
50%     50.500000   53.500000
75%     75.250000   74.250000
max    100.000000   99.000000

In [12]:
# first 5 rows
df.head()

,Index,User Id,First Name,Last Name,age,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,12,Male,elijah57@example.net,001-084-906-7849x73518,26-10-1945,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,45,Female,bethany14@example.com,214.112.6044x4913,24-03-1910,Phytotherapist
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,34,Male,bthompson@example.com,277.609.7938,02-07-1992,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,23,Male,kaitlinkaiser@example.com,584.094.6111,03-08-2017,Market researcher
4,5,1bA7A3dc874da3c,Lori,Todd,56,Male,buchananmanuel@example.net,689-207-3558x7233,01-12-1938,Veterinary surgeon

In [13]:
# last 5 rows
df.tail()

,Index,User Id,First Name,Last Name,age,Sex,Email,Phone,Date of birth,Job Title
95,96,5eFda7caAeB260E,Dennis,Barnes,64,Female,bmartin@example.org,001-095-524-2112x257,30-07-1954,Software engineer
96,97,CCbFce93d3720bE,Steve,Patterson,34,Female,latasha46@example.net,001-865-478-5157,29-04-1932,Barrister
97,98,2fEc528aFAF0b69,Wesley,Bray,34,Male,regina11@example.org,995-542-3004x76800,28-12-1994,Police officer
98,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,22,Female,alexiscantrell@example.org,001-273-685-6932x092,12-04-2012,Broadcast journalist
99,100,b8D0aD3490FC7e1,Mariah,Bernard,21,Male,pcopeland@example.org,(341)594-6554x44657,15-11-2016,IT sales professional

In [14]:
#show rows and the column
df.shape

(100, 10)

In [15]:
# to check the data type
df.dtypes

Index             int64
User Id          object
First Name       object
Last Name        object
age               int64
Sex              object
Email            object
Phone            object
Date of birth    object
Job Title        object
dtype: object

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          100 non-null    int64
 1   User Id        100 non-null    object
 2   First Name     100 non-null    object
 3   Last Name      100 non-null    object
 4   age            100 non-null    int64
 5   Sex            100 non-null    object
 6   Email          100 non-null    object
 7   Phone          100 non-null    object
 8   Date of birth  100 non-null    object
 9   Job Title      100 non-null    object
dtypes: int64(2), object(8)
memory usage: 7.9+ KB

In [17]:
df[0:100:2]

,Index,User Id,First Name,Last Name,age,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,12,Male,elijah57@example.net,001-084-906-7849x73518,26-10-1945,Games developer
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,34,Male,bthompson@example.com,277.609.7938,02-07-1992,Homeopath
4,5,1bA7A3dc874da3c,Lori,Todd,56,Male,buchananmanuel@example.net,689-207-3558x7233,01-12-1938,Veterinary surgeon
6,7,bE9EEf34cB72AF7,Katherine,Buck,15,Female,conniecowan@example.com,+1-773-151-6685x49162,22-01-1989,Intelligence analyst
8,9,baDcC4DeefD8dEB,Dave,Farrell,89,Male,nmccann@example.net,603-428-2429x27392,06-10-2018,Lawyer
10,11,BF0BbA03C29Bb3b,Sheila,Ross,23,Female,huangcathy@example.com,895.881.4746,20-03-2008,Advertising account executive
12,13,C03fDADdAadAdCe,Mandy,Blake,55,Male,jefferynoble@example.org,(992)466-1305x4947,08-12-2007,"Scientist, clinical (histocompatibility and im..."
14,15,1F0B7D65A00DAF9,Crystal,Farmer,77,Male,pmiranda@example.org,-5791,09-03-1992,Agricultural consultant
16,17,D6dbA5308fEC4BC,Maurice,Rangel,99,Male,sheenabanks@example.com,(246)187-4969,20-08-2004,Secretary/administrator
18,19,7F7E1BAcb0C9AFf,Alvin,Paul,33,Male,gilbertdonaldson@example.com,219.436.0887x07551,12-05-1949,"Teacher, adult education"
20,21,b31D271F8c200AB,Jacqueline,Norton,18,Female,carias@example.net,819.309.7679x59173,09-10-1952,"Scientist, marine"
22,23,cBbBcA0FCA3C4Bc,Randy,Barnes,30,Male,huangbill@example.org,001-960-629-7164x67214,30-12-1947,Outdoor activities/education manager
24,25,c5B09fb33e8bA0A,Alfred,Mcneil,53,Female,cassandramorris@example.com,(468)276-9509x53058,28-05-1993,Systems analyst
26,27,9c1bc7EC53Fb7cE,Louis,Payne,75,Male,bsullivan@example.net,6232695307,29-01-1916,Counsellor
28,29,66F096D36Ebae11,Judy,Buckley,97,Male,irosales@example.net,001-654-208-1241x52830,28-07-1963,Art gallery manager
30,31,5d2feAfbdCAA6B5,Isaiah,Camacho,20,Female,jimblake@example.org,001-536-544-3367,07-04-1966,Food technologist
32,33,8Ef7DBfcaB02b6B,Bonnie,Andrews,50,Female,caitlin24@example.net,+1-253-987-2776x9161,21-12-1953,Seismic interpreter
34,35,3Fb8a7f68e12784,Jackson,Sparks,70,Female,reynoldsdarryl@example.net,(137)908-3129x65035,18-11-1980,Set designer
36,37,aa614aAE4B7Cf0C,Leonard,Hurst,90,Male,clinton78@example.org,941-038-0427x38800,13-03-1938,"Accountant, chartered management"
38,39,b6a35de5CB6fc25,Cynthia,Wiggins,42,Female,rosariodave@example.org,(110)858-2437x70190,27-01-1984,Outdoor activities/education manager
40,41,7D0AcBF6CCac3fd,Matthew,Stone,62,Female,evelyn31@example.org,952-381-6360,23-08-2017,"Scientist, clinical (histocompatibility and im..."
42,43,9edBC94aE7cA22a,Willie,Vang,82,Female,haleymathews@example.net,741.168.6854x067,02-02-1978,Management consultant
44,45,5F2f3fAca8B0946,Darren,Andrews,24,Male,lhernandez@example.com,(975)799-4261,04-10-1997,Retail banker
46,47,f3BD2cBF7eEb6df,Danielle,Estrada,46,Female,jvang@example.org,(890)374-9518x772,09-07-1930,"Accountant, chartered management"
48,49,dBCEf340C3657Eb,Caitlyn,Frey,68,Male,rivasdominique@example.org,805-021-3965x46344,26-01-1968,Jewellery designer
50,51,eA3fDd79BE9f0E7,Heidi,Escobar,91,Female,staffordtravis@example.net,601-155-3065x1131,25-09-1931,Estate manager/land agent
52,53,9F5DeD7aD228F5a,Beverly,Esparza,36,Female,iphelps@example.net,+1-327-578-8754x6771,09-12-1930,Passenger transport manager
54,55,60FdBFd5e7BE8fF,Debra,Payne,58,Female,yolanda07@example.org,001-731-525-8400x52593,20-08-1927,Special educational needs teacher
56,57,CD8d33aA25bc8BB,Courtney,Watkins,81,Female,ochang@example.org,210.683.2761x5883,07-12-2003,Pension scheme manager
58,59,e552D7ddafe1FFb,Ryan,Nelson,26,Female,qnorman@example.org,956.330.2951,02-05-1924,Historic buildings inspector/conservation officer
60,61,bB9e49E506F65ed,Shari,Daugherty,48,Male,kalvarado@example.org,001-951-655-4798x6124,24-11-1944,Curator
62,63,0aBE5ACb18E0c10,Jackie,Bennett,71,Male,hutchinsonkirk@example.com,001-740-937-0846x0087,11-11-1915,Neurosurgeon
64,65,Ee6974f90eeCe18,Harold,Barnett,95,Female,nathan65@example.org,-6682,15-03-1943,"Biochemist, clinical"
66,67,9Df5Ba591bF3EFf,Mike,Ward,38,Female,imccullough@example.com,116-729-5046,09-11-1967,Hydrologist
68,69,Ebcefdf75eCb0a9,Frank,Pineda,61,Male,daltoncalvin@example.net,(035)961-5060x9182,10-03-1926,Hospital pharmacist
70,71,6a53a8D41dDF6de,Ryan,Benton,85,Male,lopezdebbie@example.org,+1-695-557-9948x485,06-10-2020,Physiological scientist
72,73,5bC87340799FBD0,Jean,Ritter,28,Female,kristina76@example.com,(954)060-1066,06-08-1985,Financial trader
74,75,c935b7Eb6FA0B0F,Kim,Andrews,51,Female,wpetersen@example.org,7677125383,15-11-1990,"Biochemist, clinical"
76,77,dade3452F0c32FD,Jonathon,Atkinson,74,Male,gailfrench@example.net,874-037-2032x932,19-07-2011,"Psychologist, forensic"
78,79,DAf111987098ae4,Regina,Stevens,19,Male,xpoole@example.net,891-359-2684,28-11-2011,Public house manager
80,81,12DCb4ED8E01D5C,Tyler,Foley,43,Female,johnathan72@example.org,001-386-469-3075x8030,19-09-1908,Economist
82,83,AedDfaE8Cf49F07,Reginald,Stephenson,65,Male,erikaball@example.net,+1-832-500-6044x475,08-02-2010,Contracting civil engineer
84,85,E883773cA5219Be,Helen,Williamson,84,Female,melvin08@example.net,001-377-726-4229,11-08-1911,"Lecturer, further education"
86,87,5834700fbEd2771,Chelsea,Dickson,13,Male,johnnyhendricks@example.net,001-698-651-0138x18588,13-05-1958,"Teacher, early years/pre"
88,89,3f3a3D89ad042Dd,Harry,Medina,33,Female,olsenmalik@example.net,-6354,24-08-1947,Technical sales engineer
90,91,F0aeC9c2759F3C6,Alison,Nixon,58,Female,zmiles@example.net,3506680871,10-07-1941,Patent attorney
92,93,2A33E7Cad1bb0F5,Melody,Cox,73,Female,evan90@example.org,(626)520-5080x3511,30-07-1974,Dance movement psychotherapist
94,95,feaBf8dAE0C0d6F,Dillon,Guzman,45,Female,angelanavarro@example.net,971-992-4521,01-04-1942,Air broker
96,97,CCbFce93d3720bE,Steve,Patterson,34,Female,latasha46@example.net,001-865-478-5157,29-04-1932,Barrister
98,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,22,Female,alexiscantrell@example.org,001-273-685-6932x092,12-04-2012,Broadcast journalist

In [18]:
df[0:100:5]

,Index,User Id,First Name,Last Name,age,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,12,Male,elijah57@example.net,001-084-906-7849x73518,26-10-1945,Games developer
5,6,bfDD7CDEF5D865B,Erin,Day,78,Male,tconner@example.org,001-171-649-9856x5553,28-10-2015,Waste management officer
10,11,BF0BbA03C29Bb3b,Sheila,Ross,23,Female,huangcathy@example.com,895.881.4746,20-03-2008,Advertising account executive
15,16,50Bb061cB30B461,Thomas,Knight,88,Female,braunpriscilla@example.net,-2005,18-02-2006,Sport and exercise psychologist
20,21,b31D271F8c200AB,Jacqueline,Norton,18,Female,carias@example.net,819.309.7679x59173,09-10-1952,"Scientist, marine"
25,26,c9F2282C40BEC1E,Sean,Levine,64,Male,sallymiller@example.net,4915828504,09-10-2010,"Conservation officer, nature"
30,31,5d2feAfbdCAA6B5,Isaiah,Camacho,20,Female,jimblake@example.org,001-536-544-3367,07-04-1966,Food technologist
35,36,035eff50B9A0F24,Melody,Cook,80,Male,jeannovak@example.org,(826)792-7381,25-06-1963,Research scientist (life sciences)
40,41,7D0AcBF6CCac3fd,Matthew,Stone,62,Female,evelyn31@example.org,952-381-6360,23-08-2017,"Scientist, clinical (histocompatibility and im..."
45,46,6bFcfc3cc1BC6B4,Haley,Pugh,35,Female,molly03@example.org,(746)182-6137x2453,16-09-1980,Commissioning editor
50,51,eA3fDd79BE9f0E7,Heidi,Escobar,91,Female,staffordtravis@example.net,601-155-3065x1131,25-09-1931,Estate manager/land agent
55,56,D8bF5Ab2b98caff,Mackenzie,Rocha,69,Female,abbottyvette@example.net,4225525458,21-10-1980,Museum/gallery exhibitions officer
60,61,bB9e49E506F65ed,Shari,Daugherty,48,Male,kalvarado@example.org,001-951-655-4798x6124,24-11-1944,Curator
65,66,cEf02C076afa07f,Larry,Harper,27,Male,maria32@example.org,+1-244-630-3792x4121,05-05-2021,"Scientist, water quality"
70,71,6a53a8D41dDF6de,Ryan,Benton,85,Male,lopezdebbie@example.org,+1-695-557-9948x485,06-10-2020,Physiological scientist
75,76,b3e15e65Ca2CcBf,Tina,Cunningham,63,Male,wongmary@example.org,079-907-5051,29-11-1956,Race relations officer
80,81,12DCb4ED8E01D5C,Tyler,Foley,43,Female,johnathan72@example.org,001-386-469-3075x8030,19-09-1908,Economist
85,86,CB19EafEbBfF9eC,Mario,Vaughn,96,Male,oblake@example.com,160-144-5039x12276,08-07-1990,Research scientist (life sciences)
90,91,F0aeC9c2759F3C6,Alison,Nixon,58,Female,zmiles@example.net,3506680871,10-07-1941,Patent attorney
95,96,5eFda7caAeB260E,Dennis,Barnes,64,Female,bmartin@example.org,001-095-524-2112x257,30-07-1954,Software engineer

In [19]:
# access rows and the column of dataframe
df.loc[0:3] # print 0 to 3

,Index,User Id,First Name,Last Name,age,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,12,Male,elijah57@example.net,001-084-906-7849x73518,26-10-1945,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,45,Female,bethany14@example.com,214.112.6044x4913,24-03-1910,Phytotherapist
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,34,Male,bthompson@example.com,277.609.7938,02-07-1992,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,23,Male,kaitlinkaiser@example.com,584.094.6111,03-08-2017,Market researcher

In [20]:
df.iloc[0:3] # print the 0 to 2

,Index,User Id,First Name,Last Name,age,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,12,Male,elijah57@example.net,001-084-906-7849x73518,26-10-1945,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,45,Female,bethany14@example.com,214.112.6044x4913,24-03-1910,Phytotherapist
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,34,Male,bthompson@example.com,277.609.7938,02-07-1992,Homeopath

In [21]:
# when wants a pertucular index and perticular column
df.loc[0:3,["Sex","Email"]]

      Sex                      Email
0    Male       elijah57@example.net
1  Female      bethany14@example.com
2    Male      bthompson@example.com
3    Male  kaitlinkaiser@example.com

In [22]:
df.iloc[0:3,["Sex","Email"]]
## when we add the column name with  the iloc it will throw an error

IndexError: .iloc requires numeric indexers, got ['Sex' 'Email']

In [ ]:
# when wants to access the three to six column then we can access them by their indexing also
df.iloc[0:3,5:7] # its indexing of the column5:7 and 0:3 is the no. ofrows
# iloc alwaya requires the python internal indexing

In [ ]:
df['Job Title'][2:5]

In [ ]:
list(df['Job Title'][2:5])

In [ ]:
pd.Series

In [ ]:
# here chnage the name of the indexing
s=pd.Series(list(df['Job Title'][2:5]), index =['a','b','c'])

In [23]:
s

NameError: name 's' is not defined

In [24]:
s1=pd.Series(list(df['Job Title'][5:8]))

In [25]:
s1

0    Waste management officer
1        Intelligence analyst
2              Hydrogeologist
dtype: object

In [26]:
"siya"+"rohit"# concate function

'siyarohit'

In [27]:
# series with diff indexing and dataframe can not be concatenated using "+"
s+s1 #.......here having the diff type of concate if the same type will be there then there will not be the nan value

NameError: name 's' is not defined

In [28]:
# if you keep the indexes some , then for  series concatination can happen
s1=pd.Series(list(df['Job Title'][5:8]),index =['a','b','c']) 
s1

a    Waste management officer
b        Intelligence analyst
c              Hydrogeologist
dtype: object

In [29]:
s=pd.Series(list(df['Job Title'][2:5]), index =['a','b','c'])
s

a             Homeopath
b     Market researcher
c    Veterinary surgeon
dtype: object

In [30]:
# now you can see the both having the same indexing here which id a, b, c now we can concatinate here
# here it added both the data together as you can see hmeopath and the waste managmnet....
s+s1 # thats why here not showing the nan values

a        HomeopathWaste management officer
b    Market researcherIntelligence analyst
c         Veterinary surgeonHydrogeologist
dtype: object

In [31]:
# when wants  to drop  the one column
# only put--df.drop("sex") 
#it will thrw an error for that need to do , # YOU can see here not having the column og the sex
df.drop('Sex', axis=1)

,Index,User Id,First Name,Last Name,age,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,12,elijah57@example.net,001-084-906-7849x73518,26-10-1945,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,45,bethany14@example.com,214.112.6044x4913,24-03-1910,Phytotherapist
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,34,bthompson@example.com,277.609.7938,02-07-1992,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,23,kaitlinkaiser@example.com,584.094.6111,03-08-2017,Market researcher
4,5,1bA7A3dc874da3c,Lori,Todd,56,buchananmanuel@example.net,689-207-3558x7233,01-12-1938,Veterinary surgeon
...,...,...,...,...,...,...,...,...,...
95,96,5eFda7caAeB260E,Dennis,Barnes,64,bmartin@example.org,001-095-524-2112x257,30-07-1954,Software engineer
96,97,CCbFce93d3720bE,Steve,Patterson,34,latasha46@example.net,001-865-478-5157,29-04-1932,Barrister
97,98,2fEc528aFAF0b69,Wesley,Bray,34,regina11@example.org,995-542-3004x76800,28-12-1994,Police officer
98,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,22,alexiscantrell@example.org,001-273-685-6932x092,12-04-2012,Broadcast journalist
99,100,b8D0aD3490FC7e1,Mariah,Bernard,21,pcopeland@example.org,(341)594-6554x44657,15-11-2016,IT sales professional

In [32]:
df 
# when you pass original data frame then you can see it here also its not deleted from the original dataframe

,Index,User Id,First Name,Last Name,age,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,12,Male,elijah57@example.net,001-084-906-7849x73518,26-10-1945,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,45,Female,bethany14@example.com,214.112.6044x4913,24-03-1910,Phytotherapist
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,34,Male,bthompson@example.com,277.609.7938,02-07-1992,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,23,Male,kaitlinkaiser@example.com,584.094.6111,03-08-2017,Market researcher
4,5,1bA7A3dc874da3c,Lori,Todd,56,Male,buchananmanuel@example.net,689-207-3558x7233,01-12-1938,Veterinary surgeon
...,...,...,...,...,...,...,...,...,...,...
95,96,5eFda7caAeB260E,Dennis,Barnes,64,Female,bmartin@example.org,001-095-524-2112x257,30-07-1954,Software engineer
96,97,CCbFce93d3720bE,Steve,Patterson,34,Female,latasha46@example.net,001-865-478-5157,29-04-1932,Barrister
97,98,2fEc528aFAF0b69,Wesley,Bray,34,Male,regina11@example.org,995-542-3004x76800,28-12-1994,Police officer
98,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,22,Female,alexiscantrell@example.org,001-273-685-6932x092,12-04-2012,Broadcast journalist
99,100,b8D0aD3490FC7e1,Mariah,Bernard,21,Male,pcopeland@example.org,(341)594-6554x44657,15-11-2016,IT sales professional

In [33]:
# when to wanna delete from the original column ( columns)
df.drop('Sex', axis=1 , inplace=True)

In [34]:
df
# now you can see here the not having the sex column it deleted from the original dataframe

,Index,User Id,First Name,Last Name,age,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,12,elijah57@example.net,001-084-906-7849x73518,26-10-1945,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,45,bethany14@example.com,214.112.6044x4913,24-03-1910,Phytotherapist
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,34,bthompson@example.com,277.609.7938,02-07-1992,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,23,kaitlinkaiser@example.com,584.094.6111,03-08-2017,Market researcher
4,5,1bA7A3dc874da3c,Lori,Todd,56,buchananmanuel@example.net,689-207-3558x7233,01-12-1938,Veterinary surgeon
...,...,...,...,...,...,...,...,...,...
95,96,5eFda7caAeB260E,Dennis,Barnes,64,bmartin@example.org,001-095-524-2112x257,30-07-1954,Software engineer
96,97,CCbFce93d3720bE,Steve,Patterson,34,latasha46@example.net,001-865-478-5157,29-04-1932,Barrister
97,98,2fEc528aFAF0b69,Wesley,Bray,34,regina11@example.org,995-542-3004x76800,28-12-1994,Police officer
98,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,22,alexiscantrell@example.org,001-273-685-6932x092,12-04-2012,Broadcast journalist
99,100,b8D0aD3490FC7e1,Mariah,Bernard,21,pcopeland@example.org,(341)594-6554x44657,15-11-2016,IT sales professional

In [35]:
#axis=1 means the drop from columns, " inplace "= true   means to modify form the original dataframe
# axis=0 means drop from rows

In [36]:
# if we wanna drop a row

In [37]:
df

,Index,User Id,First Name,Last Name,age,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,12,elijah57@example.net,001-084-906-7849x73518,26-10-1945,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,45,bethany14@example.com,214.112.6044x4913,24-03-1910,Phytotherapist
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,34,bthompson@example.com,277.609.7938,02-07-1992,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,23,kaitlinkaiser@example.com,584.094.6111,03-08-2017,Market researcher
4,5,1bA7A3dc874da3c,Lori,Todd,56,buchananmanuel@example.net,689-207-3558x7233,01-12-1938,Veterinary surgeon
...,...,...,...,...,...,...,...,...,...
95,96,5eFda7caAeB260E,Dennis,Barnes,64,bmartin@example.org,001-095-524-2112x257,30-07-1954,Software engineer
96,97,CCbFce93d3720bE,Steve,Patterson,34,latasha46@example.net,001-865-478-5157,29-04-1932,Barrister
97,98,2fEc528aFAF0b69,Wesley,Bray,34,regina11@example.org,995-542-3004x76800,28-12-1994,Police officer
98,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,22,alexiscantrell@example.org,001-273-685-6932x092,12-04-2012,Broadcast journalist
99,100,b8D0aD3490FC7e1,Mariah,Bernard,21,pcopeland@example.org,(341)594-6554x44657,15-11-2016,IT sales professional

In [38]:
df.drop(5,inplace=True)  #here is drop the row of 5 no.

In [39]:
df

,Index,User Id,First Name,Last Name,age,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,12,elijah57@example.net,001-084-906-7849x73518,26-10-1945,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,45,bethany14@example.com,214.112.6044x4913,24-03-1910,Phytotherapist
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,34,bthompson@example.com,277.609.7938,02-07-1992,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,23,kaitlinkaiser@example.com,584.094.6111,03-08-2017,Market researcher
4,5,1bA7A3dc874da3c,Lori,Todd,56,buchananmanuel@example.net,689-207-3558x7233,01-12-1938,Veterinary surgeon
...,...,...,...,...,...,...,...,...,...
95,96,5eFda7caAeB260E,Dennis,Barnes,64,bmartin@example.org,001-095-524-2112x257,30-07-1954,Software engineer
96,97,CCbFce93d3720bE,Steve,Patterson,34,latasha46@example.net,001-865-478-5157,29-04-1932,Barrister
97,98,2fEc528aFAF0b69,Wesley,Bray,34,regina11@example.org,995-542-3004x76800,28-12-1994,Police officer
98,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,22,alexiscantrell@example.org,001-273-685-6932x092,12-04-2012,Broadcast journalist
99,100,b8D0aD3490FC7e1,Mariah,Bernard,21,pcopeland@example.org,(341)594-6554x44657,15-11-2016,IT sales professional

In [40]:
df.reset_index(drop=True) # make this as it  original

,Index,User Id,First Name,Last Name,age,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,12,elijah57@example.net,001-084-906-7849x73518,26-10-1945,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,45,bethany14@example.com,214.112.6044x4913,24-03-1910,Phytotherapist
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,34,bthompson@example.com,277.609.7938,02-07-1992,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,23,kaitlinkaiser@example.com,584.094.6111,03-08-2017,Market researcher
4,5,1bA7A3dc874da3c,Lori,Todd,56,buchananmanuel@example.net,689-207-3558x7233,01-12-1938,Veterinary surgeon
...,...,...,...,...,...,...,...,...,...
94,96,5eFda7caAeB260E,Dennis,Barnes,64,bmartin@example.org,001-095-524-2112x257,30-07-1954,Software engineer
95,97,CCbFce93d3720bE,Steve,Patterson,34,latasha46@example.net,001-865-478-5157,29-04-1932,Barrister
96,98,2fEc528aFAF0b69,Wesley,Bray,34,regina11@example.org,995-542-3004x76800,28-12-1994,Police officer
97,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,22,alexiscantrell@example.org,001-273-685-6932x092,12-04-2012,Broadcast journalist
98,100,b8D0aD3490FC7e1,Mariah,Bernard,21,pcopeland@example.org,(341)594-6554x44657,15-11-2016,IT sales professional

In [41]:
# set a new index  , as see new index is the email it took the place of the index
df.set_index('Email', inplace = True)

In [42]:
df

,Index,User Id,First Name,Last Name,age,Phone,Date of birth,Job Title
Email,,,,,,,,
elijah57@example.net,1,88F7B33d2bcf9f5,Shelby,Terrell,12,001-084-906-7849x73518,26-10-1945,Games developer
bethany14@example.com,2,f90cD3E76f1A9b9,Phillip,Summers,45,214.112.6044x4913,24-03-1910,Phytotherapist
bthompson@example.com,3,DbeAb8CcdfeFC2c,Kristine,Travis,34,277.609.7938,02-07-1992,Homeopath
kaitlinkaiser@example.com,4,A31Bee3c201ef58,Yesenia,Martinez,23,584.094.6111,03-08-2017,Market researcher
buchananmanuel@example.net,5,1bA7A3dc874da3c,Lori,Todd,56,689-207-3558x7233,01-12-1938,Veterinary surgeon
...,...,...,...,...,...,...,...,...
bmartin@example.org,96,5eFda7caAeB260E,Dennis,Barnes,64,001-095-524-2112x257,30-07-1954,Software engineer
latasha46@example.net,97,CCbFce93d3720bE,Steve,Patterson,34,001-865-478-5157,29-04-1932,Barrister
regina11@example.org,98,2fEc528aFAF0b69,Wesley,Bray,34,995-542-3004x76800,28-12-1994,Police officer
alexiscantrell@example.org,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,22,001-273-685-6932x092,12-04-2012,Broadcast journalist
pcopeland@example.org,100,b8D0aD3490FC7e1,Mariah,Bernard,21,(341)594-6554x44657,15-11-2016,IT sales professional

In [43]:
# if wanna original indexning back then do only
df.reset_index()
# here got  the origanl indexing back and the email is in first column

,Email,Index,User Id,First Name,Last Name,age,Phone,Date of birth,Job Title
0,elijah57@example.net,1,88F7B33d2bcf9f5,Shelby,Terrell,12,001-084-906-7849x73518,26-10-1945,Games developer
1,bethany14@example.com,2,f90cD3E76f1A9b9,Phillip,Summers,45,214.112.6044x4913,24-03-1910,Phytotherapist
2,bthompson@example.com,3,DbeAb8CcdfeFC2c,Kristine,Travis,34,277.609.7938,02-07-1992,Homeopath
3,kaitlinkaiser@example.com,4,A31Bee3c201ef58,Yesenia,Martinez,23,584.094.6111,03-08-2017,Market researcher
4,buchananmanuel@example.net,5,1bA7A3dc874da3c,Lori,Todd,56,689-207-3558x7233,01-12-1938,Veterinary surgeon
...,...,...,...,...,...,...,...,...,...
94,bmartin@example.org,96,5eFda7caAeB260E,Dennis,Barnes,64,001-095-524-2112x257,30-07-1954,Software engineer
95,latasha46@example.net,97,CCbFce93d3720bE,Steve,Patterson,34,001-865-478-5157,29-04-1932,Barrister
96,regina11@example.org,98,2fEc528aFAF0b69,Wesley,Bray,34,995-542-3004x76800,28-12-1994,Police officer
97,alexiscantrell@example.org,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,22,001-273-685-6932x092,12-04-2012,Broadcast journalist
98,pcopeland@example.org,100,b8D0aD3490FC7e1,Mariah,Bernard,21,(341)594-6554x44657,15-11-2016,IT sales professional

In [44]:
# you can make data frame from the dictionary
d={'key1':[2,3,4],
   'key2':[5,6,7],
   'key3':[8,9,10]}

In [45]:
d

{'key1': [2, 3, 4], 'key2': [5, 6, 7], 'key3': [8, 9, 10]}

In [46]:
pd.DataFrame(d)

   key1  key2  key3
0     2     5     8
1     3     6     9
2     4     7    10

In [47]:
# tuple can also convert into the dataframe
d={'key1':(2,3,4),
   'key2':(5,6,7),
   'key3':(8,9,10)}

In [48]:
pd.DataFrame(d)

   key1  key2  key3
0     2     5     8
1     3     6     9
2     4     7    10

In [49]:
df

,Index,User Id,First Name,Last Name,age,Phone,Date of birth,Job Title
Email,,,,,,,,
elijah57@example.net,1,88F7B33d2bcf9f5,Shelby,Terrell,12,001-084-906-7849x73518,26-10-1945,Games developer
bethany14@example.com,2,f90cD3E76f1A9b9,Phillip,Summers,45,214.112.6044x4913,24-03-1910,Phytotherapist
bthompson@example.com,3,DbeAb8CcdfeFC2c,Kristine,Travis,34,277.609.7938,02-07-1992,Homeopath
kaitlinkaiser@example.com,4,A31Bee3c201ef58,Yesenia,Martinez,23,584.094.6111,03-08-2017,Market researcher
buchananmanuel@example.net,5,1bA7A3dc874da3c,Lori,Todd,56,689-207-3558x7233,01-12-1938,Veterinary surgeon
...,...,...,...,...,...,...,...,...
bmartin@example.org,96,5eFda7caAeB260E,Dennis,Barnes,64,001-095-524-2112x257,30-07-1954,Software engineer
latasha46@example.net,97,CCbFce93d3720bE,Steve,Patterson,34,001-865-478-5157,29-04-1932,Barrister
regina11@example.org,98,2fEc528aFAF0b69,Wesley,Bray,34,995-542-3004x76800,28-12-1994,Police officer
alexiscantrell@example.org,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,22,001-273-685-6932x092,12-04-2012,Broadcast journalist
pcopeland@example.org,100,b8D0aD3490FC7e1,Mariah,Bernard,21,(341)594-6554x44657,15-11-2016,IT sales professional

In [50]:
df.isnull().sum()
# there is no null value thats why it showing it zero else it will show the how many no. of null values are there like 11, 14, 15

Index            0
User Id          0
First Name       0
Last Name        0
age              0
Phone            0
Date of birth    0
Job Title        0
dtype: int64

In [51]:
pd.read_csv('mtt.csv')

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6.0,160.0,110.0,3.90,2.620,16.46,0,1.0,4,4
1,Mazda RX4 Wag,21.0,6.0,160.0,110.0,3.90,2.875,17.02,0,1.0,4,4
2,Datsun 710,22.8,NaN,108.0,93.0,NaN,2.320,NaN,1,1.0,4,1
3,Hornet 4 Drive,21.4,6.0,258.0,110.0,3.08,3.215,NaN,1,0.0,3,1
4,Hornet Sportabout,18.7,8.0,360.0,175.0,3.15,3.440,NaN,0,0.0,3,2
5,Valiant,18.1,6.0,225.0,NaN,NaN,3.460,20.22,1,NaN,3,1
6,Duster 360,14.3,NaN,NaN,NaN,3.21,3.570,15.84,0,0.0,3,4
7,Merc 240D,24.4,4.0,146.7,62.0,3.69,3.190,20.00,1,0.0,4,2
8,Merc 230,22.8,4.0,140.8,95.0,3.92,3.150,22.90,1,0.0,4,2
9,Merc 280,19.2,6.0,167.6,123.0,NaN,3.440,18.30,1,0.0,4,4
10,Merc 280C,17.8,6.0,167.6,NaN,3.92,3.440,18.90,1,0.0,4,4
11,Merc 450SE,16.4,8.0,NaN,180.0,3.07,4.070,17.40,0,0.0,3,3
12,Merc 450SL,17.3,8.0,275.8,180.0,3.07,3.730,17.60,0,0.0,3,3

In [52]:
df=(pd.read_csv('mtt.csv'))

In [53]:
df

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6.0,160.0,110.0,3.90,2.620,16.46,0,1.0,4,4
1,Mazda RX4 Wag,21.0,6.0,160.0,110.0,3.90,2.875,17.02,0,1.0,4,4
2,Datsun 710,22.8,NaN,108.0,93.0,NaN,2.320,NaN,1,1.0,4,1
3,Hornet 4 Drive,21.4,6.0,258.0,110.0,3.08,3.215,NaN,1,0.0,3,1
4,Hornet Sportabout,18.7,8.0,360.0,175.0,3.15,3.440,NaN,0,0.0,3,2
5,Valiant,18.1,6.0,225.0,NaN,NaN,3.460,20.22,1,NaN,3,1
6,Duster 360,14.3,NaN,NaN,NaN,3.21,3.570,15.84,0,0.0,3,4
7,Merc 240D,24.4,4.0,146.7,62.0,3.69,3.190,20.00,1,0.0,4,2
8,Merc 230,22.8,4.0,140.8,95.0,3.92,3.150,22.90,1,0.0,4,2
9,Merc 280,19.2,6.0,167.6,123.0,NaN,3.440,18.30,1,0.0,4,4
10,Merc 280C,17.8,6.0,167.6,NaN,3.92,3.440,18.90,1,0.0,4,4
11,Merc 450SE,16.4,8.0,NaN,180.0,3.07,4.070,17.40,0,0.0,3,3
12,Merc 450SL,17.3,8.0,275.8,180.0,3.07,3.730,17.60,0,0.0,3,3

In [54]:
df.isnull() # where obtaining the null values it shows the true

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,True,False,False,True,False,True,False,False,False,False
3,False,False,False,False,False,False,False,True,False,False,False,False
4,False,False,False,False,False,False,False,True,False,False,False,False
5,False,False,False,False,True,True,False,False,False,True,False,False
6,False,False,True,True,True,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,True,False,False,False,False,False,False
10,False,False,False,False,True,False,False,False,False,False,False,False
11,False,False,False,True,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False

In [55]:
df.isnull().sum() # here showing the in which column having the null values are there

model    0
mpg      0
cyl      2
disp     2
hp       3
drat     3
wt       0
qsec     3
vs       0
am       1
gear     0
carb     0
dtype: int64

In [56]:
df.shape

(13, 12)

In [57]:
# remove all null values from the rows
df.dropna() # the rows are dropes whuch having the null values thats why here is showing the only 5 rows which didt have the null valiue

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6.0,160.0,110.0,3.90,2.620,16.46,0,1.0,4,4
1,Mazda RX4 Wag,21.0,6.0,160.0,110.0,3.90,2.875,17.02,0,1.0,4,4
7,Merc 240D,24.4,4.0,146.7,62.0,3.69,3.190,20.00,1,0.0,4,2
8,Merc 230,22.8,4.0,140.8,95.0,3.92,3.150,22.90,1,0.0,4,2
12,Merc 450SL,17.3,8.0,275.8,180.0,3.07,3.730,17.60,0,0.0,3,3

In [58]:
# but when we wanna the drop the null value with their column then we will use
# axis=1 ---- that means you drop the column which havng the null value
# for dropping column it uses the axis=0...
df.dropna(axis=1)

                model   mpg     wt  vs  gear  carb
0           Mazda RX4  21.0  2.620   0     4     4
1       Mazda RX4 Wag  21.0  2.875   0     4     4
2          Datsun 710  22.8  2.320   1     4     1
3      Hornet 4 Drive  21.4  3.215   1     3     1
4   Hornet Sportabout  18.7  3.440   0     3     2
5             Valiant  18.1  3.460   1     3     1
6          Duster 360  14.3  3.570   0     3     4
7           Merc 240D  24.4  3.190   1     4     2
8            Merc 230  22.8  3.150   1     4     2
9            Merc 280  19.2  3.440   1     4     4
10          Merc 280C  17.8  3.440   1     4     4
11         Merc 450SE  16.4  4.070   0     3     3
12         Merc 450SL  17.3  3.730   0     3     3

In [59]:
df.info

<bound method DataFrame.info of                 model   mpg  cyl   disp     hp  drat     wt   qsec  vs   am  \
0           Mazda RX4  21.0  6.0  160.0  110.0  3.90  2.620  16.46   0  1.0
1       Mazda RX4 Wag  21.0  6.0  160.0  110.0  3.90  2.875  17.02   0  1.0
2          Datsun 710  22.8  NaN  108.0   93.0   NaN  2.320    NaN   1  1.0
3      Hornet 4 Drive  21.4  6.0  258.0  110.0  3.08  3.215    NaN   1  0.0
4   Hornet Sportabout  18.7  8.0  360.0  175.0  3.15  3.440    NaN   0  0.0
5             Valiant  18.1  6.0  225.0    NaN   NaN  3.460  20.22   1  NaN
6          Duster 360  14.3  NaN    NaN    NaN  3.21  3.570  15.84   0  0.0
7           Merc 240D  24.4  4.0  146.7   62.0  3.69  3.190  20.00   1  0.0
8            Merc 230  22.8  4.0  140.8   95.0  3.92  3.150  22.90   1  0.0
9            Merc 280  19.2  6.0  167.6  123.0   NaN  3.440  18.30   1  0.0
10          Merc 280C  17.8  6.0  167.6    NaN  3.92  3.440  18.90   1  0.0
11         Merc 450SE  16.4  8.0    NaN  180.0  3.07  4.070  17.40   0  0.0
12         Merc 450SL  17.3  8.0  275.8  180.0  3.07  3.730  17.60   0  0.0

    gear  carb
0      4     4
1      4     4
2      4     1
3      3     1
4      3     2
5      3     1
6      3     4
7      4     2
8      4     2
9      4     4
10     4     4
11     3     3
12     3     3  >

In [60]:
df.shape

(13, 12)

In [61]:
df.tail()

         model   mpg  cyl   disp     hp  drat    wt  qsec  vs   am  gear  carb
8     Merc 230  22.8  4.0  140.8   95.0  3.92  3.15  22.9   1  0.0     4     2
9     Merc 280  19.2  6.0  167.6  123.0   NaN  3.44  18.3   1  0.0     4     4
10   Merc 280C  17.8  6.0  167.6    NaN  3.92  3.44  18.9   1  0.0     4     4
11  Merc 450SE  16.4  8.0    NaN  180.0  3.07  4.07  17.4   0  0.0     3     3
12  Merc 450SL  17.3  8.0  275.8  180.0  3.07  3.73  17.6   0  0.0     3     3

In [62]:
df.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6.0,160.0,110.0,3.90,2.620,16.46,0,1.0,4,4
1,Mazda RX4 Wag,21.0,6.0,160.0,110.0,3.90,2.875,17.02,0,1.0,4,4
2,Datsun 710,22.8,NaN,108.0,93.0,NaN,2.320,NaN,1,1.0,4,1
3,Hornet 4 Drive,21.4,6.0,258.0,110.0,3.08,3.215,NaN,1,0.0,3,1
4,Hornet Sportabout,18.7,8.0,360.0,175.0,3.15,3.440,NaN,0,0.0,3,2

In [63]:
# imputation of missing values<<----replacing missing values with same values
# numeric data >>---- mean and median >> oulier (abnormal) value treatment is done , then use mean 
# categorical data  > mode
# impute missing with some constatnt , i.e -0

In [64]:
df

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6.0,160.0,110.0,3.90,2.620,16.46,0,1.0,4,4
1,Mazda RX4 Wag,21.0,6.0,160.0,110.0,3.90,2.875,17.02,0,1.0,4,4
2,Datsun 710,22.8,NaN,108.0,93.0,NaN,2.320,NaN,1,1.0,4,1
3,Hornet 4 Drive,21.4,6.0,258.0,110.0,3.08,3.215,NaN,1,0.0,3,1
4,Hornet Sportabout,18.7,8.0,360.0,175.0,3.15,3.440,NaN,0,0.0,3,2
5,Valiant,18.1,6.0,225.0,NaN,NaN,3.460,20.22,1,NaN,3,1
6,Duster 360,14.3,NaN,NaN,NaN,3.21,3.570,15.84,0,0.0,3,4
7,Merc 240D,24.4,4.0,146.7,62.0,3.69,3.190,20.00,1,0.0,4,2
8,Merc 230,22.8,4.0,140.8,95.0,3.92,3.150,22.90,1,0.0,4,2
9,Merc 280,19.2,6.0,167.6,123.0,NaN,3.440,18.30,1,0.0,4,4
10,Merc 280C,17.8,6.0,167.6,NaN,3.92,3.440,18.90,1,0.0,4,4
11,Merc 450SE,16.4,8.0,NaN,180.0,3.07,4.070,17.40,0,0.0,3,3
12,Merc 450SL,17.3,8.0,275.8,180.0,3.07,3.730,17.60,0,0.0,3,3

In [65]:
df.fillna("somevalue")
# it use when the there is some missing values are there it strt to print there is somevalue 
# we can write there anything we wanna to

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6.0,160.0,110.0,3.9,2.620,16.46,0,1.0,4,4
1,Mazda RX4 Wag,21.0,6.0,160.0,110.0,3.9,2.875,17.02,0,1.0,4,4
2,Datsun 710,22.8,somevalue,108.0,93.0,somevalue,2.320,somevalue,1,1.0,4,1
3,Hornet 4 Drive,21.4,6.0,258.0,110.0,3.08,3.215,somevalue,1,0.0,3,1
4,Hornet Sportabout,18.7,8.0,360.0,175.0,3.15,3.440,somevalue,0,0.0,3,2
5,Valiant,18.1,6.0,225.0,somevalue,somevalue,3.460,20.22,1,somevalue,3,1
6,Duster 360,14.3,somevalue,somevalue,somevalue,3.21,3.570,15.84,0,0.0,3,4
7,Merc 240D,24.4,4.0,146.7,62.0,3.69,3.190,20.0,1,0.0,4,2
8,Merc 230,22.8,4.0,140.8,95.0,3.92,3.150,22.9,1,0.0,4,2
9,Merc 280,19.2,6.0,167.6,123.0,somevalue,3.440,18.3,1,0.0,4,4
10,Merc 280C,17.8,6.0,167.6,somevalue,3.92,3.440,18.9,1,0.0,4,4
11,Merc 450SE,16.4,8.0,somevalue,180.0,3.07,4.070,17.4,0,0.0,3,3
12,Merc 450SL,17.3,8.0,275.8,180.0,3.07,3.730,17.6,0,0.0,3,3

In [66]:
df.fillna("fillmissingvalue") 
# now here we put the filllmissingvalue ehre the null value was there

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6.0,160.0,110.0,3.9,2.620,16.46,0,1.0,4,4
1,Mazda RX4 Wag,21.0,6.0,160.0,110.0,3.9,2.875,17.02,0,1.0,4,4
2,Datsun 710,22.8,fillmissingvalue,108.0,93.0,fillmissingvalue,2.320,fillmissingvalue,1,1.0,4,1
3,Hornet 4 Drive,21.4,6.0,258.0,110.0,3.08,3.215,fillmissingvalue,1,0.0,3,1
4,Hornet Sportabout,18.7,8.0,360.0,175.0,3.15,3.440,fillmissingvalue,0,0.0,3,2
5,Valiant,18.1,6.0,225.0,fillmissingvalue,fillmissingvalue,3.460,20.22,1,fillmissingvalue,3,1
6,Duster 360,14.3,fillmissingvalue,fillmissingvalue,fillmissingvalue,3.21,3.570,15.84,0,0.0,3,4
7,Merc 240D,24.4,4.0,146.7,62.0,3.69,3.190,20.0,1,0.0,4,2
8,Merc 230,22.8,4.0,140.8,95.0,3.92,3.150,22.9,1,0.0,4,2
9,Merc 280,19.2,6.0,167.6,123.0,fillmissingvalue,3.440,18.3,1,0.0,4,4
10,Merc 280C,17.8,6.0,167.6,fillmissingvalue,3.92,3.440,18.9,1,0.0,4,4
11,Merc 450SE,16.4,8.0,fillmissingvalue,180.0,3.07,4.070,17.4,0,0.0,3,3
12,Merc 450SL,17.3,8.0,275.8,180.0,3.07,3.730,17.6,0,0.0,3,3

In [67]:
# also we can replace it by the zero 
df.fillna(0)

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6.0,160.0,110.0,3.90,2.620,16.46,0,1.0,4,4
1,Mazda RX4 Wag,21.0,6.0,160.0,110.0,3.90,2.875,17.02,0,1.0,4,4
2,Datsun 710,22.8,0.0,108.0,93.0,0.00,2.320,0.00,1,1.0,4,1
3,Hornet 4 Drive,21.4,6.0,258.0,110.0,3.08,3.215,0.00,1,0.0,3,1
4,Hornet Sportabout,18.7,8.0,360.0,175.0,3.15,3.440,0.00,0,0.0,3,2
5,Valiant,18.1,6.0,225.0,0.0,0.00,3.460,20.22,1,0.0,3,1
6,Duster 360,14.3,0.0,0.0,0.0,3.21,3.570,15.84,0,0.0,3,4
7,Merc 240D,24.4,4.0,146.7,62.0,3.69,3.190,20.00,1,0.0,4,2
8,Merc 230,22.8,4.0,140.8,95.0,3.92,3.150,22.90,1,0.0,4,2
9,Merc 280,19.2,6.0,167.6,123.0,0.00,3.440,18.30,1,0.0,4,4
10,Merc 280C,17.8,6.0,167.6,0.0,3.92,3.440,18.90,1,0.0,4,4
11,Merc 450SE,16.4,8.0,0.0,180.0,3.07,4.070,17.40,0,0.0,3,3
12,Merc 450SL,17.3,8.0,275.8,180.0,3.07,3.730,17.60,0,0.0,3,3

In [68]:
data1 = {
    'A':[1,2,None,4,5,None,7,8,9,10],
    'B':[None,11,12,13,None,15,16,None,18,19]
}
df2= pd.DataFrame(data1)
df2

      A     B
0   1.0   NaN
1   2.0  11.0
2   NaN  12.0
3   4.0  13.0
4   5.0   NaN
5   NaN  15.0
6   7.0  16.0
7   8.0   NaN
8   9.0  18.0
9  10.0  19.0

In [69]:
# if you want to replace the missing value with the mean value
df2['A'].mean()

5.75

In [70]:
df2['A']

0     1.0
1     2.0
2     NaN
3     4.0
4     5.0
5     NaN
6     7.0
7     8.0
8     9.0
9    10.0
Name: A, dtype: float64

In [71]:
df2['A'].fillna(df2['A'].mean())
# here we fill the value of mean value

0     1.00
1     2.00
2     5.75
3     4.00
4     5.00
5     5.75
6     7.00
7     8.00
8     9.00
9    10.00
Name: A, dtype: float64

In [72]:
# we can replace it by the median also
df2['A'].median()

6.0

In [74]:
df2.fillna("some value")

            A           B
0         1.0  some value
1         2.0        11.0
2  some value        12.0
3         4.0        13.0
4         5.0  some value
5  some value        15.0
6         7.0        16.0
7         8.0  some value
8         9.0        18.0
9        10.0        19.0

In [77]:
df2.fillna(method="ffill") # here it will fill the value which is theprivious value 
#start seeing from the botom of the data fill

C:\Users\Ashwini Powar\AppData\Local\Temp\ipykernel_14404\2502807920.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2.fillna(method="ffill") # here it will fill the value which is theprivious value

      A     B
0   1.0   NaN
1   2.0  11.0
2   2.0  12.0
3   4.0  13.0
4   5.0  13.0
5   5.0  15.0
6   7.0  16.0
7   8.0  16.0
8   9.0  18.0
9  10.0  19.0

In [78]:
df2.fillna(method="bfill") # next line word will print in the peivious where having the nan value was
# backward fill>>

C:\Users\Ashwini Powar\AppData\Local\Temp\ipykernel_14404\90801012.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2.fillna(method="bfill")

      A     B
0   1.0  11.0
1   2.0  11.0
2   4.0  12.0
3   4.0  13.0
4   5.0  15.0
5   7.0  15.0
6   7.0  16.0
7   8.0  18.0
8   9.0  18.0
9  10.0  19.0

In [79]:
# checking duplicated row
df2.duplicated().sum()

0

In [80]:
df

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6.0,160.0,110.0,3.90,2.620,16.46,0,1.0,4,4
1,Mazda RX4 Wag,21.0,6.0,160.0,110.0,3.90,2.875,17.02,0,1.0,4,4
2,Datsun 710,22.8,NaN,108.0,93.0,NaN,2.320,NaN,1,1.0,4,1
3,Hornet 4 Drive,21.4,6.0,258.0,110.0,3.08,3.215,NaN,1,0.0,3,1
4,Hornet Sportabout,18.7,8.0,360.0,175.0,3.15,3.440,NaN,0,0.0,3,2
5,Valiant,18.1,6.0,225.0,NaN,NaN,3.460,20.22,1,NaN,3,1
6,Duster 360,14.3,NaN,NaN,NaN,3.21,3.570,15.84,0,0.0,3,4
7,Merc 240D,24.4,4.0,146.7,62.0,3.69,3.190,20.00,1,0.0,4,2
8,Merc 230,22.8,4.0,140.8,95.0,3.92,3.150,22.90,1,0.0,4,2
9,Merc 280,19.2,6.0,167.6,123.0,NaN,3.440,18.30,1,0.0,4,4
10,Merc 280C,17.8,6.0,167.6,NaN,3.92,3.440,18.90,1,0.0,4,4
11,Merc 450SE,16.4,8.0,NaN,180.0,3.07,4.070,17.40,0,0.0,3,3
12,Merc 450SL,17.3,8.0,275.8,180.0,3.07,3.730,17.60,0,0.0,3,3

In [85]:
df.std

<bound method DataFrame.std of                 model   mpg  cyl   disp     hp  drat     wt   qsec  vs   am  \
0           Mazda RX4  21.0  6.0  160.0  110.0  3.90  2.620  16.46   0  1.0
1       Mazda RX4 Wag  21.0  6.0  160.0  110.0  3.90  2.875  17.02   0  1.0
2          Datsun 710  22.8  NaN  108.0   93.0   NaN  2.320    NaN   1  1.0
3      Hornet 4 Drive  21.4  6.0  258.0  110.0  3.08  3.215    NaN   1  0.0
4   Hornet Sportabout  18.7  8.0  360.0  175.0  3.15  3.440    NaN   0  0.0
5             Valiant  18.1  6.0  225.0    NaN   NaN  3.460  20.22   1  NaN
6          Duster 360  14.3  NaN    NaN    NaN  3.21  3.570  15.84   0  0.0
7           Merc 240D  24.4  4.0  146.7   62.0  3.69  3.190  20.00   1  0.0
8            Merc 230  22.8  4.0  140.8   95.0  3.92  3.150  22.90   1  0.0
9            Merc 280  19.2  6.0  167.6  123.0   NaN  3.440  18.30   1  0.0
10          Merc 280C  17.8  6.0  167.6    NaN  3.92  3.440  18.90   1  0.0
11         Merc 450SE  16.4  8.0    NaN  180.0  3.07  4.070  17.40   0  0.0
12         Merc 450SL  17.3  8.0  275.8  180.0  3.07  3.730  17.60   0  0.0

    gear  carb
0      4     4
1      4     4
2      4     1
3      3     1
4      3     2
5      3     1
6      3     4
7      4     2
8      4     2
9      4     4
10     4     4
11     3     3
12     3     3  >

In [ ]:
#