In [2]:
import pandas as pd
import numpy as nd

In [5]:
pd.read_csv("sample_data1.csv")

      Name  Age Ticker           City  number     emailid     copany
0    Alice   25   AAPL       New York       2     gvcjhcv    infosys
1      Bob   30   MSFT  San Francisco      22     cvcjdch      wipro
2  Charlie   35  GOOGL        Chicago       3  jhv vjdch   accenture
3    Diana   40   AMZN        Seattle       4       hcdvk        tcs
4   Edward   45   TSLA         Austin       5      hcv kc     gemini

df=(pd.read_csv("sample_data1.csv"))

In [6]:
df=(pd.read_csv("sample_data1.csv"))

In [7]:
df

      Name  Age Ticker           City  number     emailid     copany
0    Alice   25   AAPL       New York       2     gvcjhcv    infosys
1      Bob   30   MSFT  San Francisco      22     cvcjdch      wipro
2  Charlie   35  GOOGL        Chicago       3  jhv vjdch   accenture
3    Diana   40   AMZN        Seattle       4       hcdvk        tcs
4   Edward   45   TSLA         Austin       5      hcv kc     gemini

In [8]:
df1=[["name","city","age"]][0:5]

df1

In [9]:
df1=[["name","city","age"]][0:5]

In [10]:
df1

[['name', 'city', 'age']]

In [11]:
df1=df[["Name","City","Age"]][0:5]

In [12]:
df2=df[["Name","City","Age"]][3:]

In [13]:
df2

     Name     City  Age
3   Diana  Seattle   40
4  Edward   Austin   45

In [14]:
df1

      Name           City  Age
0    Alice       New York   25
1      Bob  San Francisco   30
2  Charlie        Chicago   35
3    Diana        Seattle   40
4   Edward         Austin   45

In [15]:
#there are two posibilities of the concatination 
#is that first first it it concatinate as the building and second is that it concatinate as the side by side 
#for verticle concatiante it as axis=o , and for horizontal concatination along column as axis=1

In [16]:
pd.concat([df1,df2])
# it shows the verticle concatination
# by default verticle concatination

      Name           City  Age
0    Alice       New York   25
1      Bob  San Francisco   30
2  Charlie        Chicago   35
3    Diana        Seattle   40
4   Edward         Austin   45
3    Diana        Seattle   40
4   Edward         Austin   45

In [17]:
# horizontal concatination is there
pd.concat([df1,df2],axis=1)
# where indexes are not mating it getting the NAN values

      Name           City  Age    Name     City   Age
0    Alice       New York   25     NaN      NaN   NaN
1      Bob  San Francisco   30     NaN      NaN   NaN
2  Charlie        Chicago   35     NaN      NaN   NaN
3    Diana        Seattle   40   Diana  Seattle  40.0
4   Edward         Austin   45  Edward   Austin  45.0

In [18]:
# concatination means keeping two dataframe vertically or the horizontally

In [19]:
#merge
df1= pd.DataFrame({'key': [1,2,4,5,6],
                   'key2':[4,5,6,7,8],
                   'key3':[3,4,5,6,6]
                  }) 
df1

   key  key2  key3
0    1     4     3
1    2     5     4
2    4     6     5
3    5     7     6
4    6     8     6

In [20]:
df2 =pd.DataFrame({ 'key':[1,2,45,6,67],
                   'key4':[56,5,6,7,8],
                   'key5':[3,56,5,6,6]})
df2

   key  key4  key5
0    1    56     3
1    2     5    56
2   45     6     5
3    6     7     6
4   67     8     6

In [21]:
pd.merge(df1,df2,how='inner')

   key  key2  key3  key4  key5
0    1     4     3    56     3
1    2     5     4     5    56
2    6     8     6     7     6

In [22]:
pd.merge(df1,df2,how = 'left')

   key  key2  key3  key4  key5
0    1     4     3  56.0   3.0
1    2     5     4   5.0  56.0
2    4     6     5   NaN   NaN
3    5     7     6   NaN   NaN
4    6     8     6   7.0   6.0

In [23]:
pd.merge( df1,  df2, how='right')

   key  key2  key3  key4  key5
0    1   4.0   3.0    56     3
1    2   5.0   4.0     5    56
2   45   NaN   NaN     6     5
3    6   8.0   6.0     7     6
4   67   NaN   NaN     8     6

In [24]:
# all the common element of the common column from both the dataframe
pd.merge(df1, df2, how='outer')

   key  key2  key3  key4  key5
0    1   4.0   3.0  56.0   3.0
1    2   5.0   4.0   5.0  56.0
2    4   6.0   5.0   NaN   NaN
3    5   7.0   6.0   NaN   NaN
4    6   8.0   6.0   7.0   6.0
5   45   NaN   NaN   6.0   5.0
6   67   NaN   NaN   8.0   6.0

In [25]:
#merge
df1= pd.DataFrame({ 'key1': [1,2,4,5,6],
                   'key2':[4,5,6,7,8],
                   'key3':[3,4,5,6,6]},
                    index =['a','b','c','d','e']) 
df1

   key1  key2  key3
a     1     4     3
b     2     5     4
c     4     6     5
d     5     7     6
e     6     8     6

In [26]:
df2 =pd.DataFrame({ 'key6':[1,2,45,6,67],
                   'key4':[56,5,6,7,8],
                   'key5':[3,56,5,6,6]},
                   index =['a','b','c','d','e'] )
df2

   key6  key4  key5
a     1    56     3
b     2     5    56
c    45     6     5
d     6     7     6
e    67     8     6

In [27]:
pd.merge(df1,df2, how="cross")

    key1  key2  key3  key6  key4  key5
0      1     4     3     1    56     3
1      1     4     3     2     5    56
2      1     4     3    45     6     5
3      1     4     3     6     7     6
4      1     4     3    67     8     6
5      2     5     4     1    56     3
6      2     5     4     2     5    56
7      2     5     4    45     6     5
8      2     5     4     6     7     6
9      2     5     4    67     8     6
10     4     6     5     1    56     3
11     4     6     5     2     5    56
12     4     6     5    45     6     5
13     4     6     5     6     7     6
14     4     6     5    67     8     6
15     5     7     6     1    56     3
16     5     7     6     2     5    56
17     5     7     6    45     6     5
18     5     7     6     6     7     6
19     5     7     6    67     8     6
20     6     8     6     1    56     3
21     6     8     6     2     5    56
22     6     8     6    45     6     5
23     6     8     6     6     7     6
24     6     8     6    67     8     6

In [28]:
pd.merge( df1, df2, how='left' , left_on="key2" , right_on="key4")

   key1  key2  key3  key6  key4  key5
0     1     4     3   NaN   NaN   NaN
1     2     5     4   2.0   5.0  56.0
2     4     6     5  45.0   6.0   5.0
3     5     7     6   6.0   7.0   6.0
4     6     8     6  67.0   8.0   6.0

In [29]:
# join >> join works based on index/ merge works based an columns

In [30]:
df1

   key1  key2  key3
a     1     4     3
b     2     5     4
c     4     6     5
d     5     7     6
e     6     8     6

In [31]:
df2

   key6  key4  key5
a     1    56     3
b     2     5    56
c    45     6     5
d     6     7     6
e    67     8     6

In [32]:
df1.join(df2, how ='inner')
# joins columns of another dataframe based on common index

   key1  key2  key3  key6  key4  key5
a     1     4     3     1    56     3
b     2     5     4     2     5    56
c     4     6     5    45     6     5
d     5     7     6     6     7     6
e     6     8     6    67     8     6

In [33]:
df1.join(df2, how="right")

   key1  key2  key3  key6  key4  key5
a     1     4     3     1    56     3
b     2     5     4     2     5    56
c     4     6     5    45     6     5
d     5     7     6     6     7     6
e     6     8     6    67     8     6

In [34]:
df1.join(df2, how="outer")

   key1  key2  key3  key6  key4  key5
a     1     4     3     1    56     3
b     2     5     4     2     5    56
c     4     6     5    45     6     5
d     5     7     6     6     7     6
e     6     8     6    67     8     6

In [35]:
df1.join(df2, how="left")

   key1  key2  key3  key6  key4  key5
a     1     4     3     1    56     3
b     2     5     4     2     5    56
c     4     6     5    45     6     5
d     5     7     6     6     7     6
e     6     8     6    67     8     6

In [36]:
df1.join(df2, how="cross")

    key1  key2  key3  key6  key4  key5
0      1     4     3     1    56     3
1      1     4     3     2     5    56
2      1     4     3    45     6     5
3      1     4     3     6     7     6
4      1     4     3    67     8     6
5      2     5     4     1    56     3
6      2     5     4     2     5    56
7      2     5     4    45     6     5
8      2     5     4     6     7     6
9      2     5     4    67     8     6
10     4     6     5     1    56     3
11     4     6     5     2     5    56
12     4     6     5    45     6     5
13     4     6     5     6     7     6
14     4     6     5    67     8     6
15     5     7     6     1    56     3
16     5     7     6     2     5    56
17     5     7     6    45     6     5
18     5     7     6     6     7     6
19     5     7     6    67     8     6
20     6     8     6     1    56     3
21     6     8     6     2     5    56
22     6     8     6    45     6     5
23     6     8     6     6     7     6
24     6     8     6    67     8     6

In [37]:
# apply >> to apply a function on all the elements/ values of a column
#if we have the column fare having some value which we wants to convert into indian rupees
 #df["fare_inr"] = df['fare'].apply(lambda x : x*90)

In [38]:
# how to get the length of the naming 
#simply we measure length by the 
len("ram")

3

In [39]:
df["Name"]

0      Alice
1        Bob
2    Charlie
3      Diana
4     Edward
Name: Name, dtype: object

In [40]:
# by using of the aaply function 
df["Name"].apply(len)

0    5
1    3
2    7
3    5
4    6
Name: Name, dtype: int64

In [41]:
def create_flag(x):
    if x < 10:
        return "cheap"
    if x >=10 and x< 20:
        return "medium"
    else:
        return"height"

In [42]:
create_flag(21)

'height'

In [45]:
df['Name'].apply(create_fakg)

NameError: name 'create_fakg' is not defined